"""Auto-generated exhaustive staging catalog derived from schema_unified.sql.

This file extends the ingester manual-mapping surface so every unified-schema
table also has a temp-table representation in staging.
"""
from __future__ import annotations

AUTO_TARGET_TABLE_SPECS: dict[str, dict[str, object]] = {
    "actor_consent_temp": {
        "entity": "actor_consent",
        "production_table": "actor_consent",
        "description": "Mirror of actor_consent for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("actor_id", ("actor_id",)),
            ("channel", ("channel",)),
            ("consent_given", ("consent_given",)),
            ("timestamp", ("timestamp",)),
            ("source", ("source",)),
            ("document_id", ("document_id",)),
        ),
    },
    "audit_audit_log_temp": {
        "entity": "audit_audit_log",
        "production_table": "audit.audit_log",
        "description": "Mirror of audit.audit_log for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("table_name", ("table_name",)),
            ("operation", ("operation",)),
            ("row_pk", ("row_pk",)),
            ("before_data", ("before_data",)),
            ("after_data", ("after_data",)),
            ("changed_at", ("changed_at",)),
            ("changed_by", ("changed_by",)),
        ),
    },
    "audit_criteria_temp": {
        "entity": "audit_criteria",
        "production_table": "audit_criteria",
        "description": "Mirror of audit_criteria for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("template_id", ("template_id",)),
            ("code", ("code",)),
            ("question", ("question",)),
            ("max_points", ("max_points",)),
            ("is_mandatory", ("is_mandatory",)),
            ("position", ("position",)),
            ("metadata", ("metadata",)),
            ("created_by", ("created_by",)),
            ("updated_by", ("updated_by",)),
        ),
    },
    "audit_result_temp": {
        "entity": "audit_result",
        "production_table": "audit_result",
        "description": "Mirror of audit_result for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("session_id", ("session_id",)),
            ("criteria_id", ("criteria_id",)),
            ("points_awarded", ("points_awarded",)),
            ("auditor_note", ("auditor_note",)),
            ("created_by", ("created_by",)),
            ("updated_by", ("updated_by",)),
        ),
    },
    "audit_session_temp": {
        "entity": "audit_session",
        "production_table": "audit_session",
        "description": "Mirror of audit_session for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("template_id", ("template_id",)),
            ("auditor_id", ("auditor_id",)),
            ("audit_date", ("audit_date",)),
            ("total_score", ("total_score",)),
            ("status", ("status",)),
            ("certified_at", ("certified_at",)),
            ("metadata", ("metadata",)),
            ("created_by", ("created_by",)),
            ("updated_by", ("updated_by",)),
        ),
    },
    "audit_template_temp": {
        "entity": "audit_template",
        "production_table": "audit_template",
        "description": "Mirror of audit_template for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("scheme_id", ("scheme_id",)),
            ("classification_value_id", ("classification_value_id",)),
            ("code", ("code",)),
            ("name", ("name",)),
            ("passing_score_required", ("passing_score_required",)),
            ("is_active", ("is_active",)),
            ("metadata", ("metadata",)),
            ("created_by", ("created_by",)),
            ("updated_by", ("updated_by",)),
        ),
    },
    "i18n_translation_temp": {
        "entity": "i18n_translation",
        "production_table": "i18n_translation",
        "description": "Mirror of i18n_translation for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("target_table", ("target_table",)),
            ("target_pk", ("target_pk",)),
            ("target_column", ("target_column",)),
            ("language_id", ("language_id",)),
            ("value_text", ("value_text",)),
            ("value_json", ("value_json",)),
        ),
    },
    "incident_report_temp": {
        "entity": "incident_report",
        "production_table": "incident_report",
        "description": "Mirror of incident_report for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("category_id", ("category_id",)),
            ("geom", ("geom",)),
            ("description", ("description",)),
            ("reporter_email", ("reporter_email",)),
            ("reporter_name", ("reporter_name",)),
            ("media_urls", ("media_urls",)),
            ("severity", ("severity",)),
            ("status", ("status",)),
            ("crm_task_id", ("crm_task_id",)),
            ("crm_interaction_id", ("crm_interaction_id",)),
            ("metadata", ("metadata",)),
            ("created_by", ("created_by",)),
            ("updated_by", ("updated_by",)),
        ),
    },
    "media_tag_temp": {
        "entity": "media_tag",
        "production_table": "media_tag",
        "description": "Mirror of media_tag for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("media_id", ("media_id",)),
            ("tag_id", ("tag_id",)),
        ),
    },
    "meeting_room_equipment_temp": {
        "entity": "meeting_room_equipment",
        "production_table": "meeting_room_equipment",
        "description": "Mirror of meeting_room_equipment for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("room_id", ("room_id",)),
            ("equipment_id", ("equipment_id",)),
            ("position", ("position",)),
            ("note", ("note",)),
        ),
    },
    "object_discount_temp": {
        "entity": "object_discount",
        "production_table": "object_discount",
        "description": "Mirror of object_discount for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("conditions", ("conditions",)),
            ("discount_percent", ("discount_percent",)),
            ("discount_amount", ("discount_amount",)),
            ("currency", ("currency",)),
            ("min_group_size", ("min_group_size",)),
            ("max_group_size", ("max_group_size",)),
            ("valid_from", ("valid_from",)),
            ("valid_to", ("valid_to",)),
            ("source", ("source",)),
        ),
    },
    "object_fma_occurrence_temp": {
        "entity": "object_fma_occurrence",
        "production_table": "object_fma_occurrence",
        "description": "Mirror of object_fma_occurrence for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("start_at", ("start_at",)),
            ("end_at", ("end_at",)),
            ("state", ("state",)),
            ("note", ("note",)),
        ),
    },
    "object_group_policy_temp": {
        "entity": "object_group_policy",
        "production_table": "object_group_policy",
        "description": "Mirror of object_group_policy for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("min_size", ("min_size",)),
            ("max_size", ("max_size",)),
            ("group_only", ("group_only",)),
            ("notes", ("notes",)),
        ),
    },
    "object_iti_associated_object_temp": {
        "entity": "object_iti_associated_object",
        "production_table": "object_iti_associated_object",
        "description": "Mirror of object_iti_associated_object for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("associated_object_id", ("associated_object_id",)),
            ("role_id", ("role_id",)),
            ("note", ("note",)),
        ),
    },
    "object_iti_info_temp": {
        "entity": "object_iti_info",
        "production_table": "object_iti_info",
        "description": "Mirror of object_iti_info for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("access", ("access",)),
            ("ambiance", ("ambiance",)),
            ("recommended_parking", ("recommended_parking",)),
            ("required_equipment", ("required_equipment",)),
            ("info_places", ("info_places",)),
            ("is_child_friendly", ("is_child_friendly",)),
            ("access_i18n", ("access_i18n",)),
            ("ambiance_i18n", ("ambiance_i18n",)),
            ("recommended_parking_i18n", ("recommended_parking_i18n",)),
            ("required_equipment_i18n", ("required_equipment_i18n",)),
            ("info_places_i18n", ("info_places_i18n",)),
        ),
    },
    "object_iti_practice_temp": {
        "entity": "object_iti_practice",
        "production_table": "object_iti_practice",
        "description": "Mirror of object_iti_practice for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("practice_id", ("practice_id",)),
        ),
    },
    "object_iti_profile_temp": {
        "entity": "object_iti_profile",
        "production_table": "object_iti_profile",
        "description": "Mirror of object_iti_profile for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("position_m", ("position_m",)),
            ("elevation_m", ("elevation_m",)),
        ),
    },
    "object_iti_section_temp": {
        "entity": "object_iti_section",
        "production_table": "object_iti_section",
        "description": "Mirror of object_iti_section for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("parent_object_id", ("parent_object_id",)),
            ("name", ("name",)),
            ("position", ("position",)),
            ("geom", ("geom",)),
        ),
    },
    "object_iti_stage_temp": {
        "entity": "object_iti_stage",
        "production_table": "object_iti_stage",
        "description": "Mirror of object_iti_stage for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("name", ("name",)),
            ("description", ("description",)),
            ("position", ("position",)),
            ("geom", ("geom",)),
            ("description_i18n", ("description_i18n",)),
        ),
    },
    "object_iti_stage_media_temp": {
        "entity": "object_iti_stage_media",
        "production_table": "object_iti_stage_media",
        "description": "Mirror of object_iti_stage_media for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("stage_id", ("stage_id",)),
            ("media_id", ("media_id",)),
            ("position", ("position",)),
        ),
    },
    "object_meeting_room_temp": {
        "entity": "object_meeting_room",
        "production_table": "object_meeting_room",
        "description": "Mirror of object_meeting_room for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("name", ("name",)),
            ("area_m2", ("area_m2",)),
            ("cap_theatre", ("cap_theatre",)),
            ("cap_u", ("cap_u",)),
            ("cap_classroom", ("cap_classroom",)),
            ("cap_boardroom", ("cap_boardroom",)),
        ),
    },
    "object_menu_temp": {
        "entity": "object_menu",
        "production_table": "object_menu",
        "description": "Mirror of object_menu for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("category_id", ("category_id",)),
            ("name", ("name",)),
            ("description", ("description",)),
            ("is_active", ("is_active",)),
            ("visibility", ("visibility",)),
            ("position", ("position",)),
        ),
    },
    "object_menu_item_temp": {
        "entity": "object_menu_item",
        "production_table": "object_menu_item",
        "description": "Mirror of object_menu_item for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("menu_id", ("menu_id",)),
            ("name", ("name",)),
            ("description", ("description",)),
            ("price", ("price",)),
            ("currency", ("currency",)),
            ("kind_id", ("kind_id",)),
            ("unit_id", ("unit_id",)),
            ("media_id", ("media_id",)),
            ("is_available", ("is_available",)),
            ("position", ("position",)),
        ),
    },
    "object_menu_item_allergen_temp": {
        "entity": "object_menu_item_allergen",
        "production_table": "object_menu_item_allergen",
        "description": "Mirror of object_menu_item_allergen for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("menu_item_id", ("menu_item_id",)),
            ("allergen_id", ("allergen_id",)),
        ),
    },
    "object_menu_item_cuisine_type_temp": {
        "entity": "object_menu_item_cuisine_type",
        "production_table": "object_menu_item_cuisine_type",
        "description": "Mirror of object_menu_item_cuisine_type for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("menu_item_id", ("menu_item_id",)),
            ("cuisine_type_id", ("cuisine_type_id",)),
        ),
    },
    "object_menu_item_dietary_tag_temp": {
        "entity": "object_menu_item_dietary_tag",
        "production_table": "object_menu_item_dietary_tag",
        "description": "Mirror of object_menu_item_dietary_tag for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("menu_item_id", ("menu_item_id",)),
            ("dietary_tag_id", ("dietary_tag_id",)),
        ),
    },
    "object_menu_item_media_temp": {
        "entity": "object_menu_item_media",
        "production_table": "object_menu_item_media",
        "description": "Mirror of object_menu_item_media for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("menu_item_id", ("menu_item_id",)),
            ("media_id", ("media_id",)),
            ("position", ("position",)),
        ),
    },
    "object_pet_policy_temp": {
        "entity": "object_pet_policy",
        "production_table": "object_pet_policy",
        "description": "Mirror of object_pet_policy for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("accepted", ("accepted",)),
            ("conditions", ("conditions",)),
        ),
    },
    "object_place_temp": {
        "entity": "object_place",
        "production_table": "object_place",
        "description": "Mirror of object_place for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("label", ("label",)),
            ("slug", ("slug",)),
            ("is_primary", ("is_primary",)),
            ("position", ("position",)),
            ("effective_from", ("effective_from",)),
            ("effective_to", ("effective_to",)),
            ("extra", ("extra",)),
        ),
    },
    "object_place_description_temp": {
        "entity": "object_place_description",
        "production_table": "object_place_description",
        "description": "Mirror of object_place_description for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("place_id", ("place_id",)),
            ("description", ("description",)),
            ("description_chapo", ("description_chapo",)),
            ("description_mobile", ("description_mobile",)),
            ("description_edition", ("description_edition",)),
            ("description_offre_hors_zone", ("description_offre_hors_zone",)),
            ("sanitary_measures", ("sanitary_measures",)),
            ("description_adapted", ("description_adapted",)),
            ("visibility", ("visibility",)),
            ("position", ("position",)),
            ("extra", ("extra",)),
            ("description_chapo_i18n", ("description_chapo_i18n",)),
            ("description_mobile_i18n", ("description_mobile_i18n",)),
            ("description_edition_i18n", ("description_edition_i18n",)),
            ("description_offre_hors_zone_i18n", ("description_offre_hors_zone_i18n",)),
            ("sanitary_measures_i18n", ("sanitary_measures_i18n",)),
            ("description_adapted_i18n", ("description_adapted_i18n",)),
        ),
    },
    "object_price_period_temp": {
        "entity": "object_price_period",
        "production_table": "object_price_period",
        "description": "Mirror of object_price_period for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("price_id", ("price_id",)),
            ("start_date", ("start_date",)),
            ("end_date", ("end_date",)),
            ("start_time", ("start_time",)),
            ("end_time", ("end_time",)),
            ("note", ("note",)),
        ),
    },
    "object_private_description_temp": {
        "entity": "object_private_description",
        "production_table": "object_private_description",
        "description": "Mirror of object_private_description for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("org_object_id", ("org_object_id",)),
            ("body", ("body",)),
            ("audience", ("audience",)),
            ("language_id", ("language_id",)),
        ),
    },
    "object_relation_temp": {
        "entity": "object_relation",
        "production_table": "object_relation",
        "description": "Mirror of object_relation for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("source_object_id", ("source_object_id",)),
            ("target_object_id", ("target_object_id",)),
            ("relation_type_id", ("relation_type_id",)),
            ("distance_m", ("distance_m",)),
            ("note", ("note",)),
            ("position", ("position",)),
        ),
    },
    "object_room_type_amenity_temp": {
        "entity": "object_room_type_amenity",
        "production_table": "object_room_type_amenity",
        "description": "Mirror of object_room_type_amenity for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("room_type_id", ("room_type_id",)),
            ("amenity_id", ("amenity_id",)),
        ),
    },
    "object_room_type_media_temp": {
        "entity": "object_room_type_media",
        "production_table": "object_room_type_media",
        "description": "Mirror of object_room_type_media for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("room_type_id", ("room_type_id",)),
            ("media_id", ("media_id",)),
            ("position", ("position",)),
        ),
    },
    "object_sustainability_action_temp": {
        "entity": "object_sustainability_action",
        "production_table": "object_sustainability_action",
        "description": "Mirror of object_sustainability_action for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("action_id", ("action_id",)),
            ("document_id", ("document_id",)),
            ("note", ("note",)),
        ),
    },
    "object_sustainability_action_label_temp": {
        "entity": "object_sustainability_action_label",
        "production_table": "object_sustainability_action_label",
        "description": "Mirror of object_sustainability_action_label for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("object_sustainability_action_id", ("object_sustainability_action_id",)),
            ("object_classification_id", ("object_classification_id",)),
        ),
    },
    "object_version_temp": {
        "entity": "object_version",
        "production_table": "object_version",
        "description": "Mirror of object_version for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("version_number", ("version_number",)),
            ("data", ("data",)),
            ("created_by", ("created_by",)),
            ("change_reason", ("change_reason",)),
            ("change_type", ("change_type",)),
        ),
    },
    "object_zone_temp": {
        "entity": "object_zone",
        "production_table": "object_zone",
        "description": "Mirror of object_zone for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("insee_commune", ("insee_commune",)),
            ("position", ("position",)),
        ),
    },
    "opening_schedule_temp": {
        "entity": "opening_schedule",
        "production_table": "opening_schedule",
        "description": "Mirror of opening_schedule for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("period_id", ("period_id",)),
            ("schedule_type_id", ("schedule_type_id",)),
            ("name", ("name",)),
            ("note", ("note",)),
            ("note_i18n", ("note_i18n",)),
        ),
    },
    "opening_time_frame_temp": {
        "entity": "opening_time_frame",
        "production_table": "opening_time_frame",
        "description": "Mirror of opening_time_frame for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("time_period_id", ("time_period_id",)),
            ("start_time", ("start_time",)),
            ("end_time", ("end_time",)),
            ("recurrence", ("recurrence",)),
        ),
    },
    "opening_time_period_temp": {
        "entity": "opening_time_period",
        "production_table": "opening_time_period",
        "description": "Mirror of opening_time_period for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("schedule_id", ("schedule_id",)),
            ("closed", ("closed",)),
            ("note", ("note",)),
        ),
    },
    "opening_time_period_weekday_temp": {
        "entity": "opening_time_period_weekday",
        "production_table": "opening_time_period_weekday",
        "description": "Mirror of opening_time_period_weekday for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("time_period_id", ("time_period_id",)),
            ("weekday_id", ("weekday_id",)),
        ),
    },
    "pending_change_temp": {
        "entity": "pending_change",
        "production_table": "pending_change",
        "description": "Mirror of pending_change for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("target_table", ("target_table",)),
            ("target_pk", ("target_pk",)),
            ("action", ("action",)),
            ("payload", ("payload",)),
            ("submitted_by", ("submitted_by",)),
            ("submitted_at", ("submitted_at",)),
            ("status", ("status",)),
            ("reviewed_by", ("reviewed_by",)),
            ("reviewed_at", ("reviewed_at",)),
            ("review_note", ("review_note",)),
            ("applied_at", ("applied_at",)),
            ("metadata", ("metadata",)),
        ),
    },
    "promotion_temp": {
        "entity": "promotion",
        "production_table": "promotion",
        "description": "Mirror of promotion for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("code", ("code",)),
            ("name", ("name",)),
            ("name_i18n", ("name_i18n",)),
            ("description", ("description",)),
            ("description_i18n", ("description_i18n",)),
            ("type_id", ("type_id",)),
            ("discount_type", ("discount_type",)),
            ("discount_value", ("discount_value",)),
            ("currency", ("currency",)),
            ("valid_from", ("valid_from",)),
            ("valid_to", ("valid_to",)),
            ("max_uses", ("max_uses",)),
            ("max_uses_per_user", ("max_uses_per_user",)),
            ("current_uses", ("current_uses",)),
            ("min_purchase_amount", ("min_purchase_amount",)),
            ("applicable_object_types", ("applicable_object_types",)),
            ("season_id", ("season_id",)),
            ("partner_org_id", ("partner_org_id",)),
            ("is_active", ("is_active",)),
            ("is_public", ("is_public",)),
            ("created_by", ("created_by",)),
        ),
    },
    "promotion_object_temp": {
        "entity": "promotion_object",
        "production_table": "promotion_object",
        "description": "Mirror of promotion_object for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("promotion_id", ("promotion_id",)),
        ),
    },
    "promotion_usage_temp": {
        "entity": "promotion_usage",
        "production_table": "promotion_usage",
        "description": "Mirror of promotion_usage for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("promotion_id", ("promotion_id",)),
            ("user_id", ("user_id",)),
            ("used_at", ("used_at",)),
            ("amount_saved", ("amount_saved",)),
            ("currency", ("currency",)),
        ),
    },
    "publication_temp": {
        "entity": "publication",
        "production_table": "publication",
        "description": "Mirror of publication for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("code", ("code",)),
            ("name", ("name",)),
            ("target_audience", ("target_audience",)),
            ("year", ("year",)),
            ("status", ("status",)),
            ("metadata", ("metadata",)),
            ("created_by", ("created_by",)),
            ("updated_by", ("updated_by",)),
        ),
    },
    "publication_object_temp": {
        "entity": "publication_object",
        "production_table": "publication_object",
        "description": "Mirror of publication_object for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("publication_id", ("publication_id",)),
            ("custom_print_text", ("custom_print_text",)),
            ("workflow_status", ("workflow_status",)),
            ("page_number", ("page_number",)),
            ("proof_sent_at", ("proof_sent_at",)),
            ("validated_bat_at", ("validated_bat_at",)),
            ("metadata", ("metadata",)),
            ("created_by", ("created_by",)),
            ("updated_by", ("updated_by",)),
        ),
    },
    "ref_actor_role_temp": {
        "entity": "ref_actor_role",
        "production_table": "ref_actor_role",
        "description": "Mirror of ref_actor_role for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("code", ("code",)),
            ("name", ("name",)),
            ("description", ("description",)),
            ("position", ("position",)),
        ),
    },
    "ref_amenity_temp": {
        "entity": "ref_amenity",
        "production_table": "ref_amenity",
        "description": "Mirror of ref_amenity for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("code", ("code",)),
            ("name", ("name",)),
            ("family_id", ("family_id",)),
            ("scope", ("scope",)),
            ("description", ("description",)),
            ("icon_url", ("icon_url",)),
            ("position", ("position",)),
            ("name_i18n", ("name_i18n",)),
        ),
    },
    "ref_capacity_applicability_temp": {
        "entity": "ref_capacity_applicability",
        "production_table": "ref_capacity_applicability",
        "description": "Mirror of ref_capacity_applicability for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("metric_id", ("metric_id",)),
            ("object_type", ("object_type",)),
        ),
    },
    "ref_capacity_metric_temp": {
        "entity": "ref_capacity_metric",
        "production_table": "ref_capacity_metric",
        "description": "Mirror of ref_capacity_metric for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("code", ("code",)),
            ("name", ("name",)),
            ("unit", ("unit",)),
            ("icon_url", ("icon_url",)),
            ("position", ("position",)),
            ("description", ("description",)),
        ),
    },
    "ref_contact_role_temp": {
        "entity": "ref_contact_role",
        "production_table": "ref_contact_role",
        "description": "Mirror of ref_contact_role for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("code", ("code",)),
            ("name", ("name",)),
            ("description", ("description",)),
            ("position", ("position",)),
        ),
    },
    "ref_document_temp": {
        "entity": "ref_document",
        "production_table": "ref_document",
        "description": "Mirror of ref_document for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("url", ("url",)),
            ("title", ("title",)),
            ("issuer", ("issuer",)),
            ("description", ("description",)),
            ("icon_url", ("icon_url",)),
            ("position", ("position",)),
            ("valid_from", ("valid_from",)),
            ("valid_to", ("valid_to",)),
            ("issuer_i18n", ("issuer_i18n",)),
            ("description_i18n", ("description_i18n",)),
        ),
    },
    "ref_iti_assoc_role_temp": {
        "entity": "ref_iti_assoc_role",
        "production_table": "ref_iti_assoc_role",
        "description": "Mirror of ref_iti_assoc_role for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("code", ("code",)),
            ("name", ("name",)),
            ("description", ("description",)),
            ("position", ("position",)),
        ),
    },
    "ref_language_temp": {
        "entity": "ref_language",
        "production_table": "ref_language",
        "description": "Mirror of ref_language for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("code", ("code",)),
            ("name", ("name",)),
            ("native_name", ("native_name",)),
            ("icon_url", ("icon_url",)),
            ("position", ("position",)),
        ),
    },
    "ref_legal_type_temp": {
        "entity": "ref_legal_type",
        "production_table": "ref_legal_type",
        "description": "Mirror of ref_legal_type for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("code", ("code",)),
            ("name", ("name",)),
            ("description", ("description",)),
            ("category", ("category",)),
            ("is_required", ("is_required",)),
            ("is_public", ("is_public",)),
            ("review_interval_days", ("review_interval_days",)),
        ),
    },
    "ref_object_relation_type_temp": {
        "entity": "ref_object_relation_type",
        "production_table": "ref_object_relation_type",
        "description": "Mirror of ref_object_relation_type for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("code", ("code",)),
            ("name", ("name",)),
            ("description", ("description",)),
            ("position", ("position",)),
        ),
    },
    "ref_org_role_temp": {
        "entity": "ref_org_role",
        "production_table": "ref_org_role",
        "description": "Mirror of ref_org_role for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("code", ("code",)),
            ("name", ("name",)),
            ("description", ("description",)),
            ("position", ("position",)),
        ),
    },
    "ref_review_source_temp": {
        "entity": "ref_review_source",
        "production_table": "ref_review_source",
        "description": "Mirror of ref_review_source for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("code", ("code",)),
            ("name", ("name",)),
            ("icon_url", ("icon_url",)),
            ("base_url", ("base_url",)),
        ),
    },
    "ref_sustainability_action_temp": {
        "entity": "ref_sustainability_action",
        "production_table": "ref_sustainability_action",
        "description": "Mirror of ref_sustainability_action for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("category_id", ("category_id",)),
            ("code", ("code",)),
            ("label", ("label",)),
            ("description", ("description",)),
            ("icon_url", ("icon_url",)),
            ("position", ("position",)),
            ("label_i18n", ("label_i18n",)),
            ("description_i18n", ("description_i18n",)),
        ),
    },
    "ref_sustainability_action_category_temp": {
        "entity": "ref_sustainability_action_category",
        "production_table": "ref_sustainability_action_category",
        "description": "Mirror of ref_sustainability_action_category for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("code", ("code",)),
            ("name", ("name",)),
            ("description", ("description",)),
            ("icon_url", ("icon_url",)),
            ("position", ("position",)),
            ("name_i18n", ("name_i18n",)),
        ),
    },
    "ref_tag_temp": {
        "entity": "ref_tag",
        "production_table": "ref_tag",
        "description": "Mirror of ref_tag for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("slug", ("slug",)),
            ("name", ("name",)),
            ("description", ("description",)),
            ("color", ("color",)),
            ("icon", ("icon",)),
            ("icon_url", ("icon_url",)),
            ("position", ("position",)),
            ("created_by", ("created_by",)),
            ("updated_by", ("updated_by",)),
            ("extra", ("extra",)),
            ("name_normalized", ("name_normalized",)),
            ("description_normalized", ("description_normalized",)),
        ),
    },
    "tag_link_temp": {
        "entity": "tag_link",
        "production_table": "tag_link",
        "description": "Mirror of tag_link for exhaustive staging/manual mapping coverage.",
        "allowed_transforms": ("identity", "lowercase", "split_list"),
        "columns": (
            ("tag_id", ("tag_id",)),
            ("target_table", ("target_table",)),
            ("target_pk", ("target_pk",)),
            ("created_by", ("created_by",)),
            ("extra", ("extra",)),
        ),
    },
}
