"""Render the unified graph into agent markdown (FUNCTIONS/POLICIES/TYPES/INDEX) and an
interactive d3 force-graph HTML. Committed artifacts carry no function bodies."""
import json


def _by(nodes, kind):
    return [n for n in nodes if n["kind"] == kind]


def write_functions_md(g):
    fns = sorted(_by(g["nodes"], "function"), key=lambda n: (n["schema"], n["label"]))
    rw = {}
    for e in g["edges"]:
        if e["kind"] in ("reads", "writes"):
            rw.setdefault(e["source"], []).append((e["kind"], e["target"], e["props"]["inference"]["confidence"]))
    out = ["# Functions / RPCs\n", "_Reads/writes are regex-inferred and flagged by confidence._\n"]
    for n in fns:
        out.append("## `%s.%s`" % (n["schema"], n["props"]["signature"]))
        meta = []
        if n["props"]["security_definer"]:
            meta.append("SECURITY DEFINER")
        if n["props"]["dynamic_sql"]:
            meta.append("dynamic SQL")
        out.append("- returns: `%s`%s" % (n["props"]["returns"], (" — " + ", ".join(meta)) if meta else ""))
        touched = rw.get(n["id"], [])
        for kind, target, conf in sorted(touched):
            out.append("- %s `%s` _(%s)_" % (kind, target, conf))
        if n["doc"]:
            out.append("\n> " + n["doc"].replace("\n", "\n> "))
        out.append("")
    return "\n".join(out)


def write_policies_md(g):
    pol = _by(g["nodes"], "policy")
    by_table = {}
    for p in pol:
        by_table.setdefault(p["props"]["table"], []).append(p)
    out = ["# RLS policies (by table)\n"]
    for tbl in sorted(by_table):
        out.append("## `%s`" % tbl)
        for p in sorted(by_table[tbl], key=lambda x: (x["props"]["cmd"], x["label"])):
            out.append("- **%s** `%s` — roles %s\n  - `%s`" % (
                p["props"]["cmd"], p["label"], p["props"]["roles"], p["props"]["predicate"]))
        out.append("")
    return "\n".join(out)


def write_types_md(g):
    enums = _by(g["nodes"], "enum")
    applies = {}
    for e in g["edges"]:
        if e["kind"] == "applies_to":
            applies.setdefault(e["props"]["object_type"], []).append(e["target"])
    out = ["# Enums & the object-model rule\n"]
    for en in sorted(enums, key=lambda n: n["label"]):
        out.append("## `%s.%s`" % (en["schema"], en["label"]))
        out.append("- values: " + ", ".join("`%s`" % v for v in en["props"]["values"]))
        out.append("")
    if applies:
        out.append("## Type → facet applicability (`ref_facet_applicability`)\n")
        for ot in sorted(applies):
            out.append("- `%s` → %s" % (ot, ", ".join("`%s`" % t for t in sorted(applies[ot]))))
    return "\n".join(out)


def write_index_md(g):
    m = g["meta"]
    out = ["# Database knowledge graph — index\n",
           "Generated by `tools/db-graph/db_graph.py` (tbls + glue). See the design spec.\n",
           "## Counts",
           "- tables: %d · views: %d · functions: %d · policies: %d · triggers: %d · enums: %d · edges: %d" % (
               m["table_count"], m["view_count"], m["function_count"], m["policy_count"],
               m["trigger_count"], m["enum_count"], m["edge_count"]),
           "\n## Artifacts",
           "- `dbdoc/` — per-table docs + ER (tbls)",
           "- `db-graph-out/FUNCTIONS.md` · `POLICIES.md` · `TYPES.md` — the glue (functions/policies/enums)",
           "- `db-graph-out/graph.json` — the unified model · `graph.html` — interactive force graph",
           "\n## Tables by domain"]
    by_dom = {}
    for n in g["nodes"]:
        if n["kind"] == "table":
            by_dom.setdefault(n["domain"], []).append(n["label"])
    for dom in sorted(by_dom):
        out.append("- **%s**: %s" % (dom, ", ".join("`%s`" % t for t in sorted(by_dom[dom]))))
    return "\n".join(out)


_HTML = """<!doctype html><meta charset="utf-8"><title>DB graph</title>
<style>body{font:13px sans-serif;margin:0}#side{position:fixed;right:0;top:0;width:300px;height:100%;
overflow:auto;border-left:1px solid #ddd;padding:8px;background:#fff}#f{padding:6px}
.n{cursor:pointer}text{pointer-events:none;font-size:9px}</style>
<div id="f"><input id="q" placeholder="search…" oninput="hl()"> <span id="meta"></span></div>
<svg id="svg" width="100%" height="640"></svg><div id="side"></div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/7.8.5/d3.min.js"></script>
<script>
const G = __GRAPH__;
const COLOR = {table:"#1D9E75",view:"#5DCAA5",matview:"#5DCAA5",enum:"#7F77DD",function:"#D85A30",policy:"#378ADD",trigger:"#BA7517"};
document.getElementById("meta").textContent = G.meta.table_count+" tables · "+G.meta.function_count+" fns · "+G.meta.policy_count+" policies";
const svg=d3.select("#svg"), W=svg.node().clientWidth, H=640;
const link=svg.append("g").attr("stroke","#bbb").attr("stroke-opacity",.4).selectAll("line").data(G.edges).join("line");
const node=svg.append("g").selectAll("circle").data(G.nodes).join("circle").attr("class","n")
  .attr("r",d=>d.kind==="table"?6:4).attr("fill",d=>COLOR[d.kind]||"#888").on("click",(e,d)=>detail(d));
const label=svg.append("g").selectAll("text").data(G.nodes).join("text").text(d=>d.label).attr("dx",6).attr("dy",3);
const sim=d3.forceSimulation(G.nodes).force("link",d3.forceLink(G.edges).id(d=>d.id).distance(40))
  .force("charge",d3.forceManyBody().strength(-60)).force("center",d3.forceCenter(W/2,H/2));
sim.on("tick",()=>{link.attr("x1",d=>d.source.x).attr("y1",d=>d.source.y).attr("x2",d=>d.target.x).attr("y2",d=>d.target.y);
  node.attr("cx",d=>d.x).attr("cy",d=>d.y);label.attr("x",d=>d.x).attr("y",d=>d.y);});
node.call(d3.drag().on("start",(e,d)=>{if(!e.active)sim.alphaTarget(.3).restart();d.fx=d.x;d.fy=d.y;})
  .on("drag",(e,d)=>{d.fx=e.x;d.fy=e.y;}).on("end",(e,d)=>{if(!e.active)sim.alphaTarget(0);d.fx=null;d.fy=null;}));
function hl(){const q=document.getElementById("q").value.toLowerCase();
  node.attr("opacity",d=>!q||d.id.toLowerCase().includes(q)?1:.1);
  label.attr("opacity",d=>!q||d.id.toLowerCase().includes(q)?1:.1);}
function detail(d){const s=document.getElementById("side");let h="<h3>"+d.label+"</h3><p>"+d.kind+" · "+d.schema+" · "+d.domain+"</p>";
  if(d.doc)h+="<pre style='white-space:pre-wrap'>"+d.doc+"</pre>";
  if(d.props.columns)h+="<ul>"+d.props.columns.map(c=>"<li>"+c.name+" : "+c.type+(c.pk?" 🔑":"")+"</li>").join("")+"</ul>";
  if(d.props.signature)h+="<p><code>"+d.props.signature+" → "+d.props.returns+"</code></p>";
  if(d.props.values)h+="<p>"+d.props.values.join(", ")+"</p>";
  if(d.props.predicate)h+="<pre style='white-space:pre-wrap'>"+d.props.predicate+"</pre>";
  s.innerHTML=h;}
</script>"""


def render_html(g):
    return _HTML.replace("__GRAPH__", json.dumps(g))
