"""Render the unified graph into agent markdown (FUNCTIONS/POLICIES/TYPES/INDEX), a
reader-facing API/DB reference page, and an interactive d3 force-graph HTML.
Committed artifacts carry no function bodies."""
from collections import defaultdict
import html as _html
import json
import re


def _by(nodes, kind):
    return [n for n in nodes if n["kind"] == kind]


def write_functions_md(g):
    fns = sorted(_by(g["nodes"], "function"), key=lambda n: (n["schema"], n["label"]))
    rw = {}
    for e in g["edges"]:
        if e["kind"] in ("reads", "writes"):
            rw.setdefault(e["source"], []).append((e["kind"], e["target"], e["props"]["inference"]["confidence"]))
    out = ["# Functions / RPCs\n", "_Reads/writes are regex-inferred and flagged by confidence._\n"]
    for n in fns:
        out.append("## `%s.%s`" % (n["schema"], n["props"]["signature"]))
        meta = []
        if n["props"]["security_definer"]:
            meta.append("SECURITY DEFINER")
        if n["props"]["dynamic_sql"]:
            meta.append("dynamic SQL")
        out.append("- returns: `%s`%s" % (n["props"]["returns"], (" — " + ", ".join(meta)) if meta else ""))
        touched = rw.get(n["id"], [])
        for kind, target, conf in sorted(touched):
            out.append("- %s `%s` _(%s)_" % (kind, target, conf))
        if n["doc"]:
            out.append("\n> " + n["doc"].replace("\n", "\n> "))
        out.append("")
    return "\n".join(out)


def write_policies_md(g):
    pol = _by(g["nodes"], "policy")
    by_table = {}
    for p in pol:
        by_table.setdefault(p["props"]["table"], []).append(p)
    out = ["# RLS policies (by table)\n"]
    for tbl in sorted(by_table):
        out.append("## `%s`" % tbl)
        for p in sorted(by_table[tbl], key=lambda x: (x["props"]["cmd"], x["label"])):
            out.append("- **%s%s** `%s` — roles %s\n  - `%s`" % (
                p["props"]["cmd"], " RESTRICTIVE" if p["props"].get("restrictive") else "",
                p["label"], p["props"]["roles"], p["props"]["predicate"]))
        out.append("")
    return "\n".join(out)


def write_types_md(g):
    enums = _by(g["nodes"], "enum")
    applies = {}
    for e in g["edges"]:
        if e["kind"] == "applies_to":
            applies.setdefault(e["props"]["object_type"], []).append(e["target"])
    out = ["# Enums & the object-model rule\n"]
    for en in sorted(enums, key=lambda n: n["label"]):
        out.append("## `%s.%s`" % (en["schema"], en["label"]))
        out.append("- values: " + ", ".join("`%s`" % v for v in en["props"]["values"]))
        out.append("")
    if applies:
        out.append("## Type → facet applicability (`ref_facet_applicability`)\n")
        for ot in sorted(applies):
            out.append("- `%s` → %s" % (ot, ", ".join("`%s`" % t for t in sorted(applies[ot]))))
    return "\n".join(out)


def write_index_md(g):
    m = g["meta"]
    out = ["# Database knowledge graph — index\n",
           "Generated by `tools/db-graph/db_graph.py` (tbls + glue). See the design spec.\n",
           "## Counts",
           "- tables: %d · views: %d · functions: %d · policies: %d · triggers: %d · enums: %d · edges: %d" % (
               m["table_count"], m["view_count"], m["function_count"], m["policy_count"],
               m["trigger_count"], m["enum_count"], m["edge_count"]),
           "\n## Artifacts",
           "- `dbdoc/` — per-table docs + ER (tbls)",
           "- `db-graph-out/FUNCTIONS.md` · `POLICIES.md` · `TYPES.md` — the glue (functions/policies/enums)",
           "- `db-graph-out/graph.json` — the unified model · `graph.html` — interactive force graph",
           "\n## Tables by domain"]
    by_dom = {}
    for n in g["nodes"]:
        if n["kind"] == "table":
            by_dom.setdefault(n["domain"], []).append(n["label"])
    for dom in sorted(by_dom):
        out.append("- **%s**: %s" % (dom, ", ".join("`%s`" % t for t in sorted(by_dom[dom]))))
    return "\n".join(out)


def _esc(value):
    return _html.escape("" if value is None else str(value), quote=True)


def _slug(value):
    return re.sub(r"[^a-z0-9_-]+", "-", str(value).lower()).strip("-") or "item"


def _node_title(node):
    if not node:
        return ""
    if node["kind"] == "function":
        return "%s.%s" % (node["schema"], node["props"]["signature"])
    return "%s.%s" % (node["schema"], node["label"])


def _short_list(values, limit=10):
    values = [v for v in values if v]
    if len(values) <= limit:
        return ", ".join("<code>%s</code>" % _esc(v) for v in values)
    shown = ", ".join("<code>%s</code>" % _esc(v) for v in values[:limit])
    return "%s <span class=\"muted\">+%d</span>" % (shown, len(values) - limit)


def _source_label(source):
    if not source:
        return ""
    path = str(source.get("path", "")).replace("\\", "/")
    marker = "Base de donnée DLL et API/"
    if marker in path:
        path = marker + path.split(marker, 1)[1]
    elif "/tools/db-graph/" in path:
        path = "tools/db-graph/" + path.split("/tools/db-graph/", 1)[1]
    if source.get("line"):
        return "%s:%s" % (path, source["line"])
    return path


def _source_html(props):
    sources = props.get("sources") or ([props["source"]] if props.get("source") else [])
    if not sources:
        return "<span class=\"muted\">non retrouvée dans les SQL versionnés</span>"
    return "<br>".join("<code>%s</code>" % _esc(_source_label(source)) for source in sources)


def _reference_key(row):
    vals = row.get("values", {})
    if vals.get("domain") and vals.get("code"):
        return "%s:%s" % (vals.get("domain"), vals.get("code"))
    if vals.get("classification_code") and vals.get("action_external_code"):
        return "%s:%s" % (vals.get("classification_code"), vals.get("action_external_code"))
    if vals.get("classification_code") and vals.get("group_code"):
        return "%s:%s" % (vals.get("classification_code"), vals.get("group_code"))
    if vals.get("category_code") and vals.get("group_code") and vals.get("external_code"):
        return "%s:%s:%s" % (vals.get("category_code"), vals.get("group_code"), vals.get("external_code"))
    if vals.get("category_code") and vals.get("group_code") and vals.get("code"):
        return "%s:%s:%s" % (vals.get("category_code"), vals.get("group_code"), vals.get("code"))
    if vals.get("scheme_code") and vals.get("code"):
        return "%s:%s" % (vals.get("scheme_code"), vals.get("code"))
    for key in ("slug", "code", "external_code", "category_code", "scheme_code"):
        if vals.get(key):
            return str(vals.get(key))
    return row.get("source", "")


def _reference_label(row):
    vals = row.get("values", {})
    for key in ("name", "label", "native_name", "description"):
        if vals.get(key):
            return vals.get(key)
    return ""


def _reference_description(row):
    vals = row.get("values", {})
    for key in ("description", "note", "category", "selection", "display_group"):
        if vals.get(key):
            return vals.get(key)
    return ""


def _small_code_list(values, limit=12):
    values = list(values)
    if not values:
        return "<span class=\"muted\">aucun</span>"
    shown = ", ".join("<code>%s</code>" % _esc(value) for value in values[:limit])
    if len(values) > limit:
        shown += " <span class=\"muted\">+%d</span>" % (len(values) - limit)
    return shown


def _live_error_parts(error):
    if isinstance(error, dict):
        return error.get("table", ""), error.get("message", "")
    return "", str(error)


def render_api_db_reference_html(g, reference_extract=None, live_note="TBLS_DSN not checked"):
    """Render a deterministic HTML reference from graph.json + versioned seed rows."""
    reference_extract = reference_extract or {"rows": [], "derived_sources": []}
    live_meta = reference_extract.get("live") or {"status": "not_queried", "tables": []}
    seed_meta = reference_extract.get("seed") or {}
    ref_rows = sorted(reference_extract.get("rows", []), key=lambda r: (r["table"], _reference_key(r), r["source"]))
    derived_sources = sorted(reference_extract.get("derived_sources", []), key=lambda r: (r["table"], r["source"]))
    nodes = {n["id"]: n for n in g["nodes"]}

    function_edges = defaultdict(list)
    read_by_table = defaultdict(list)
    write_by_table = defaultdict(list)
    policies_by_table = defaultdict(list)
    triggers_by_table = defaultdict(list)
    trigger_exec_by_function = defaultdict(list)
    fk_out = defaultdict(list)
    fk_in = defaultdict(list)
    applies = defaultdict(list)

    for edge in g["edges"]:
        kind = edge["kind"]
        src = edge["source"]
        tgt = edge["target"]
        if kind in ("reads", "writes"):
            conf = edge.get("props", {}).get("inference", {}).get("confidence", "?")
            function_edges[src].append((kind, tgt, conf))
            fn = nodes.get(src)
            name = _node_title(fn)
            if kind == "reads":
                read_by_table[tgt].append(name)
            else:
                write_by_table[tgt].append(name)
        elif kind == "gates":
            policies_by_table[tgt].append(src)
        elif kind == "trigger_on":
            triggers_by_table[tgt].append(src)
        elif kind == "executes":
            trigger_exec_by_function[tgt].append(src)
        elif kind == "fk":
            fk_out[src].append(tgt)
            fk_in[tgt].append(src)
        elif kind == "applies_to":
            applies[edge.get("props", {}).get("object_type", "?")].append(tgt)

    functions_by_schema = defaultdict(list)
    for n in g["nodes"]:
        if n["kind"] == "function":
            functions_by_schema[n["schema"]].append(n)
    for schema in functions_by_schema:
        functions_by_schema[schema].sort(key=lambda n: n["props"]["signature"])

    table_like = [n for n in g["nodes"] if n["kind"] in ("table", "view", "matview")]
    table_like.sort(key=lambda n: (n["domain"] or "", n["schema"], n["label"]))
    ref_tables = [n for n in table_like if n["domain"] == "ref-lookups" or n["label"].startswith("ref_")]

    rows_by_domain = defaultdict(list)
    rows_by_table = defaultdict(list)
    for row in ref_rows:
        vals = row.get("values", {})
        rows_by_table[row["table"]].append(row)
        domain = vals.get("domain")
        if domain:
            rows_by_domain[domain].append(row)

    rows_without_domain = [r for r in ref_rows if not r.get("values", {}).get("domain")]
    rows_without_domain_by_table = defaultdict(list)
    for row in rows_without_domain:
        rows_without_domain_by_table[row["table"]].append(row)

    all_functions = sorted(_by(g["nodes"], "function"), key=lambda n: (n["schema"], n["props"]["signature"]))
    functions_without_source = [
        _node_title(n) for n in all_functions
        if not (n.get("props", {}).get("source") or n.get("props", {}).get("sources"))
    ]
    functions_without_edges = [_node_title(n) for n in all_functions if not function_edges.get(n["id"])]
    dynamic_functions = [_node_title(n) for n in all_functions if n.get("props", {}).get("dynamic_sql")]
    tables_with_rows = {row["table"] for row in ref_rows}
    public_ref_tables_without_rows = [
        n["id"] for n in ref_tables
        if n["schema"] == "public"
        and n["id"] not in tables_with_rows
        and not (n["label"].startswith("ref_code_") and n["label"] not in ("ref_code_domain_registry", "ref_code_taxonomy_closure"))
    ]

    def live_status_html():
        status = live_meta.get("status", "not_queried")
        if status == "queried":
            parts = [
                "Lecture live effectuée sur %d tables publiques de référence." % len(live_meta.get("tables") or []),
                "%d lignes seed SQL restent disponibles pour les tables non interrogées." % seed_meta.get("rows", 0),
            ]
            if live_meta.get("truncated"):
                parts.append("%d table(s) tronquée(s) par limite de sécurité." % len(live_meta["truncated"]))
            if live_meta.get("errors"):
                parts.append("%d erreur(s) de lecture live, seeds conservés pour ces tables." % len(live_meta["errors"]))
            return " ".join(parts)
        if status == "error":
            return "Lecture live demandée mais échouée ; les valeurs affichées viennent des seeds SQL versionnées. Erreur : %s" % _esc(live_meta.get("message", "non précisée"))
        return "Aucune lecture live : les valeurs affichées viennent des seeds SQL versionnées."

    def coverage_gaps_html():
        out = ["<details><summary>Écarts de couverture à surveiller</summary>"]
        out.append("<table><thead><tr><th>Signal</th><th>Volume</th><th>Exemples</th></tr></thead><tbody>")
        rows = [
            ("Fonctions sans source SQL retrouvée", functions_without_source),
            ("Fonctions sans lecture/écriture inférée", functions_without_edges),
            ("Fonctions avec SQL dynamique", dynamic_functions),
            ("Tables publiques de référence sans ligne directe extraite", public_ref_tables_without_rows),
        ]
        for label, values in rows:
            out.append("<tr><td>%s</td><td>%d</td><td>%s</td></tr>" % (_esc(label), len(values), _small_code_list(values)))
        out.append("</tbody></table>")
        if live_meta.get("errors"):
            out.append("<h3>Erreurs de lecture live</h3><table><thead><tr><th>Table</th><th>Erreur</th></tr></thead><tbody>")
            for err in live_meta["errors"][:40]:
                table, message = _live_error_parts(err)
                out.append("<tr><td><code>%s</code></td><td>%s</td></tr>" % (_esc(table), _esc(message)))
            out.append("</tbody></table>")
        if live_meta.get("truncated"):
            out.append("<h3>Tables live tronquées</h3><table><thead><tr><th>Table</th><th>Limite</th></tr></thead><tbody>")
            for row in live_meta["truncated"]:
                out.append("<tr><td><code>%s</code></td><td>%s</td></tr>" % (_esc(row.get("table", "")), _esc(row.get("limit", ""))))
            out.append("</tbody></table>")
        out.append("</details>")
        return "\n".join(out)

    def function_block(n):
        touched = sorted(function_edges.get(n["id"], []), key=lambda item: (item[0], item[1]))
        meta = []
        if n["props"].get("security_definer"):
            meta.append("SECURITY DEFINER")
        if n["props"].get("dynamic_sql"):
            meta.append("dynamic SQL")
        lines = [
            "<details class=\"rpc\" data-search=\"%s\">" % _esc((_node_title(n) + " " + " ".join(t[1] for t in touched)).lower()),
            "<summary><code>%s.%s</code></summary>" % (_esc(n["schema"]), _esc(n["props"]["signature"])),
            "<div class=\"detail-grid\">",
            "<p><b>Retour</b><br><code>%s</code></p>" % _esc(n["props"].get("returns", "")),
            "<p><b>Propriétés</b><br>%s</p>" % (_esc(", ".join(meta)) if meta else "<span class=\"muted\">standard</span>"),
            "<p><b>Exposition</b><br>%s</p>" % ("RPC PostgREST (<code>api</code>)" if n["schema"] == "api" else "helper / privé"),
            "<p><b>Source SQL</b><br>%s</p>" % _source_html(n["props"]),
            "</div>",
        ]
        if n.get("doc"):
            lines.append("<blockquote>%s</blockquote>" % _esc(n["doc"]))
        if touched:
            lines.append("<table><thead><tr><th>Connexion</th><th>Table/vue</th><th>Confiance</th></tr></thead><tbody>")
            for kind, target, conf in touched:
                target_node = nodes.get(target)
                label = _node_title(target_node) if target_node else target
                lines.append("<tr><td>%s</td><td><a href=\"#table-%s\"><code>%s</code></a></td><td>%s</td></tr>" % (
                    "lecture" if kind == "reads" else "écriture", _slug(target), _esc(label), _esc(conf)))
            lines.append("</tbody></table>")
        else:
            lines.append("<p class=\"muted\">Aucune lecture/écriture inférée par le graphe. Cas fréquent pour les helpers purs, triggers simples ou SQL dynamique non analysable.</p>")
        trigger_callers = sorted(trigger_exec_by_function.get(n["id"], []))
        if trigger_callers:
            lines.append("<p><b>Déclenchée par</b><br>%s</p>" % _short_list(trigger_callers, 12))
        lines.append("</details>")
        return "\n".join(lines)

    def table_row(n):
        tid = n["id"]
        return (
            "<tr id=\"table-%s\"><td><code>%s</code></td><td>%s</td><td>%s</td>"
            "<td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>"
        ) % (
            _slug(tid),
            _esc(_node_title(n)),
            _esc(n["kind"]),
            _esc(n["domain"] or ""),
            "oui" if n["props"].get("rls_enabled") else "non",
            _short_list(sorted(set(read_by_table.get(tid, []))), 4) or "<span class=\"muted\">-</span>",
            _short_list(sorted(set(write_by_table.get(tid, []))), 4) or "<span class=\"muted\">-</span>",
            "%d policies · %d triggers · FK → %d · FK ← %d" % (
                len(policies_by_table.get(tid, [])),
                len(triggers_by_table.get(tid, [])),
                len(fk_out.get(tid, [])),
                len(fk_in.get(tid, [])),
            ),
        )

    def enum_section():
        enums = sorted(_by(g["nodes"], "enum"), key=lambda n: (n["schema"], n["label"]))
        out = ["<div class=\"grid cards\">"]
        for en in enums:
            out.append("<article class=\"mini-card\"><h3><code>%s.%s</code></h3><p>%s</p></article>" % (
                _esc(en["schema"]), _esc(en["label"]), _short_list(en["props"].get("values", []), 60)))
        out.append("</div>")
        if applies:
            out.append("<h3>Applicabilité des facettes par type d'objet</h3><table><thead><tr><th>Type</th><th>Tables de facette autorisées</th></tr></thead><tbody>")
            for object_type in sorted(applies):
                out.append("<tr><td><code>%s</code></td><td>%s</td></tr>" % (
                    _esc(object_type), _short_list(sorted(applies[object_type]), 30)))
            out.append("</tbody></table>")
        return "\n".join(out)

    def reference_table(rows):
        out = ["<table><thead><tr><th>Code/CID</th><th>Libellé</th><th>Description / contexte</th><th>Source</th></tr></thead><tbody>"]
        for row in rows:
            out.append("<tr><td><code>%s</code></td><td>%s</td><td>%s</td><td><code>%s</code></td></tr>" % (
                _esc(_reference_key(row)),
                _esc(_reference_label(row)),
                _esc(_reference_description(row)),
                _esc(row.get("source", "")),
            ))
        out.append("</tbody></table>")
        return "\n".join(out)

    def rls_section():
        by_table = defaultdict(list)
        for node in _by(g["nodes"], "policy"):
            by_table[node["props"].get("table", "")].append(node)
        out = ["<section id=\"rls\"><h2>3) Policies RLS par table</h2>",
               "<p>Les predicates longs sont tronqués dans le graphe généré ; la source complète reste <code>db-graph-out/catalog_extra.json</code> ou la vue live <code>pg_policies</code>.</p>"]
        for table in sorted(by_table):
            policies = sorted(by_table[table], key=lambda p: (p["props"].get("cmd", ""), p["label"]))
            out.append("<details><summary><code>%s</code> (%d policies)</summary>" % (_esc(table), len(policies)))
            out.append("<table><thead><tr><th>Commande</th><th>Policy</th><th>Rôles</th><th>Mode</th><th>Predicate</th></tr></thead><tbody>")
            for policy in policies:
                props = policy["props"]
                out.append("<tr><td><code>%s</code></td><td><code>%s</code></td><td>%s</td><td>%s</td><td><code>%s</code></td></tr>" % (
                    _esc(props.get("cmd", "")),
                    _esc(policy["label"]),
                    _esc(", ".join(props.get("roles") or [])),
                    "RESTRICTIVE" if props.get("restrictive") else "PERMISSIVE",
                    _esc(props.get("predicate", "")),
                ))
            out.append("</tbody></table></details>")
        out.append("</section>")
        return "\n".join(out)

    html = [
        "<!doctype html>",
        "<html lang=\"fr\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">",
        "<title>Bertel · Référence API, RPC et DB</title>",
        "<style>",
        ":root{--bg:#f7fbf8;--card:#fff;--text:#17211b;--muted:#68756d;--line:#dce8df;--brand:#76B097;--code:#0b1020;--codefg:#edf4ef}",
        "@media(prefers-color-scheme:dark){:root{--bg:#0b1110;--card:#101a17;--text:#e7efe9;--muted:#9fb0a6;--line:#22332a;--code:#070b12;--codefg:#edf4ef}}",
        "*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.55 Inter,system-ui,Segoe UI,Arial,sans-serif}a{color:#4f8c72;text-decoration:none}a:hover{text-decoration:underline}",
        "header{position:sticky;top:0;z-index:2;background:linear-gradient(135deg,#76B097,#5A8B73);color:white;padding:18px 24px;box-shadow:0 8px 28px #0002}header .wrap{max-width:1180px;margin:auto;display:flex;gap:18px;justify-content:space-between;align-items:center}h1{margin:0;font-size:24px}header p{margin:4px 0 0;color:#eef8f1}",
        "main{max-width:1180px;margin:24px auto 80px;padding:0 18px;display:grid;grid-template-columns:280px 1fr;gap:22px}.toc{position:sticky;top:92px;align-self:start;background:var(--card);border:1px solid var(--line);border-radius:8px;padding:16px}.toc a{display:block;margin:6px 0}",
        "section,.card,details{background:var(--card);border:1px solid var(--line);border-radius:8px;box-shadow:0 4px 18px #0000000d}section{padding:18px;margin-bottom:18px}details{padding:0;margin:10px 0}summary{cursor:pointer;padding:12px 14px;font-weight:700}details>*:not(summary){margin-left:14px;margin-right:14px}details table{margin-bottom:14px}",
        "table{width:100%;border-collapse:collapse;font-size:12px}th,td{border-bottom:1px solid var(--line);padding:8px;text-align:left;vertical-align:top}th{color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.02em}code{background:var(--code);color:var(--codefg);border-radius:4px;padding:1px 4px;font-size:.92em}blockquote{margin:10px 0;padding:10px 12px;border-left:4px solid var(--brand);background:color-mix(in srgb,var(--brand) 10%,transparent)}",
        ".grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px}.mini-card{border:1px solid var(--line);border-radius:8px;padding:12px;background:color-mix(in srgb,var(--card) 92%,var(--brand))}.mini-card h3{margin:0 0 6px;font-size:14px}.metric{font-size:24px;font-weight:800}.muted{color:var(--muted)}.detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}input{width:100%;border:1px solid #ffffff66;border-radius:8px;padding:10px 12px;background:white;color:#111}",
        "@media(max-width:900px){main{grid-template-columns:1fr}.toc{position:static}.detail-grid{grid-template-columns:1fr}header .wrap{display:block}header input{margin-top:12px}}",
        "</style></head><body>",
        "<header><div class=\"wrap\"><div><h1>Référence API, RPC et base de données</h1><p>Inventaire généré depuis <code>db-graph-out/graph.json</code> et les seeds SQL versionnées.</p></div><div><input id=\"q\" placeholder=\"Filtrer les RPC par nom ou table...\"></div></div></header>",
        "<main><nav class=\"toc\"><b>Navigation</b><a href=\"#coverage\">Couverture</a><a href=\"#rpcs\">RPC / fonctions</a><a href=\"#tables\">Connexions tables</a><a href=\"#rls\">RLS policies</a><a href=\"#enums\">Enums & types</a><a href=\"#refs\">CID, tags, refcodes</a><a href=\"#ref-tables\">Tables de référence</a><a href=\"index.html\">Retour doc API</a></nav><div>",
        "<section id=\"coverage\"><h2>0) Couverture et sources</h2>",
        "<div class=\"grid cards\">",
        "<article class=\"mini-card\"><div class=\"metric\">%d</div><b>tables</b><p class=\"muted\">%d vues · %d enums</p></article>" % (g["meta"]["table_count"], g["meta"]["view_count"], g["meta"]["enum_count"]),
        "<article class=\"mini-card\"><div class=\"metric\">%d</div><b>fonctions/RPC</b><p class=\"muted\">%d policies · %d triggers</p></article>" % (g["meta"]["function_count"], g["meta"]["policy_count"], g["meta"]["trigger_count"]),
        "<article class=\"mini-card\"><div class=\"metric\">%d</div><b>valeurs référentielles</b><p class=\"muted\">live si disponible, seeds sinon</p></article>" % len(ref_rows),
        "<article class=\"mini-card\"><div class=\"metric\">%d</div><b>connexions graphe</b><p class=\"muted\">lectures, écritures, FK, RLS</p></article>" % g["meta"]["edge_count"],
        "</div>",
        "<p>Les lectures/écritures des fonctions sont inférées par analyse SQL et portent un niveau de confiance. Les valeurs de référentiel listées ici viennent de la base live quand <code>TBLS_DSN</code> est disponible, sinon des <code>INSERT ... VALUES</code> et CTE <code>VALUES</code> versionnés dans les SQL du dépôt.</p>",
        "<p class=\"muted\">État connexion live au moment de la génération : %s. Pour valider les lignes réellement présentes en production, régénérer le graphe avec <code>TBLS_DSN</code> puis relancer <code>.tools/python/Scripts/python.exe tools/db-graph/db_graph.py</code>.</p>" % _esc(live_note),
        "<p class=\"muted\">%s</p>" % live_status_html(),
        coverage_gaps_html(),
        "</section>",
        "<section id=\"rpcs\"><h2>1) RPC / fonctions et connexions base</h2><p>Chaque bloc liste le retour, les propriétés de sécurité, le commentaire SQL disponible, puis les tables lues ou écrites.</p>",
    ]

    schema_order = sorted(functions_by_schema, key=lambda s: (s != "api", s))
    for schema in schema_order:
        html.append("<h3>Schéma <code>%s</code> (%d)</h3>" % (_esc(schema), len(functions_by_schema[schema])))
        for fn in functions_by_schema[schema]:
            html.append(function_block(fn))
    html.append("</section>")

    html.extend([
        "<section id=\"tables\"><h2>2) Connexions par table/vue</h2>",
        "<table><thead><tr><th>Table/vue</th><th>Type</th><th>Domaine</th><th>RLS</th><th>Lue par</th><th>Écrite par</th><th>Autres connexions</th></tr></thead><tbody>",
    ])
    for table in table_like:
        html.append(table_row(table))
    html.append("</tbody></table></section>")

    html.append(rls_section())

    html.append("<section id=\"enums\"><h2>4) Types, enums et applicabilité</h2>%s</section>" % enum_section())

    html.append("<section id=\"refs\"><h2>5) CID, tags, refcodes et valeurs de référence</h2>")
    html.append("<p>Dans cette documentation, <b>Code/CID</b> désigne la clé stable exposée aux API : <code>domain:code</code> pour <code>ref_code</code>, <code>slug</code> pour <code>ref_tag</code>, ou <code>code</code>/<code>external_code</code> selon la table de référence.</p>")
    if rows_by_domain:
        html.append("<h3>Domaines <code>ref_code</code></h3>")
        for domain in sorted(rows_by_domain):
            rows = rows_by_domain[domain]
            html.append("<details><summary><code>%s</code> (%d valeurs)</summary>%s</details>" % (
                _esc(domain), len(rows), reference_table(rows)))
    if rows_without_domain_by_table:
        html.append("<h3>Autres référentiels versionnés</h3>")
        for table in sorted(rows_without_domain_by_table):
            rows = rows_without_domain_by_table[table]
            html.append("<details><summary><code>%s</code> (%d valeurs)</summary>%s</details>" % (
                _esc(table), len(rows), reference_table(rows)))
    if derived_sources:
        html.append("<details><summary>Sources dérivées non listées ligne par ligne (%d)</summary><table><thead><tr><th>Table</th><th>Source</th><th>Note</th></tr></thead><tbody>" % len(derived_sources))
        for source in derived_sources:
            html.append("<tr><td><code>%s</code></td><td><code>%s</code></td><td>%s</td></tr>" % (
                _esc(source["table"]), _esc(source["source"]), _esc(source["note"])))
        html.append("</tbody></table></details>")
    html.append("</section>")

    html.append("<section id=\"ref-tables\"><h2>6) Tables de référence du graphe</h2><p>Ces tables portent les référentiels. Les colonnes affichées aident à retrouver les identifiants techniques, codes, libellés et relations.</p>")
    for table in ref_tables:
        cols = table["props"].get("columns", [])
        html.append("<details><summary><code>%s</code> · %s · RLS %s</summary>" % (
            _esc(_node_title(table)), _esc(table.get("domain") or ""), "oui" if table["props"].get("rls_enabled") else "non"))
        html.append("<table><thead><tr><th>Colonne</th><th>Type</th><th>Nullable</th><th>PK</th></tr></thead><tbody>")
        for col in cols:
            html.append("<tr><td><code>%s</code></td><td>%s</td><td>%s</td><td>%s</td></tr>" % (
                _esc(col.get("name")), _esc(col.get("type")), "oui" if col.get("nullable") else "non", "oui" if col.get("pk") else "non"))
        html.append("</tbody></table></details>")
    html.append("</section>")

    html.extend([
        "</div></main>",
        "<script>const q=document.getElementById('q');q.addEventListener('input',()=>{const v=q.value.trim().toLowerCase();document.querySelectorAll('details.rpc').forEach(d=>{d.style.display=!v||d.dataset.search.includes(v)?'block':'none';});});</script>",
        "</body></html>",
    ])
    return "\n".join(html)


# Interactive viewer: dark/light theme, kind + domain + schema filters, d3 zoom/pan,
# click-to-highlight neighborhood with a clickable connections list in the side panel.
_HTML = """<!doctype html><html><head><meta charset="utf-8"><title>DB graph</title>
<style>
:root{--bg:#0d1117;--panel:rgba(22,27,34,.92);--fg:#d7dde5;--muted:#8b949e;--border:#30363d;
  --edge:#46506033;--edge-solid:#465060;--hl:#ffb454;--chip:#21262d;--code:#161b22}
[data-theme="light"]{--bg:#ffffff;--panel:rgba(246,248,250,.95);--fg:#1f2328;--muted:#656d76;
  --border:#d0d7de;--edge:#9aa3ad55;--edge-solid:#9aa3ad;--hl:#e36209;--chip:#eaeef2;--code:#f6f8fa}
html,body{margin:0;height:100%;background:var(--bg);color:var(--fg);font:13px/1.45 system-ui,"Segoe UI",sans-serif;overflow:hidden}
#svg{position:fixed;inset:0;width:100%;height:100%;cursor:grab}
#svg:active{cursor:grabbing}
#bar{position:fixed;left:0;top:0;right:320px;z-index:2;padding:8px 10px;background:var(--panel);
  border-bottom:1px solid var(--border);backdrop-filter:blur(4px)}
#bar input{background:var(--chip);border:1px solid var(--border);color:var(--fg);border-radius:6px;
  padding:3px 8px;width:220px;outline:none}
#meta{color:var(--muted);margin-left:8px}
#theme,#fit{float:right;cursor:pointer;background:var(--chip);border:1px solid var(--border);color:var(--fg);
  border-radius:6px;padding:3px 10px;margin-left:6px}
.row{margin-top:6px;display:flex;align-items:baseline;gap:6px;flex-wrap:wrap}
.rowlab{color:var(--muted);font-size:11px;text-transform:uppercase;width:64px;flex:none}
.chips{display:flex;flex-wrap:wrap;gap:4px}
.chip{cursor:pointer;border:1px solid var(--border);background:var(--chip);border-radius:12px;
  padding:1px 9px;user-select:none;display:inline-flex;align-items:center;gap:5px;font-size:12px}
.chip.off{opacity:.4;filter:grayscale(.7)}
.chip .ct{color:var(--muted);font-size:10px}
.mini{cursor:pointer;color:var(--muted);font-size:11px;text-decoration:underline;user-select:none}
.dot{width:8px;height:8px;border-radius:50%;display:inline-block;flex:none}
#side{position:fixed;right:0;top:0;width:320px;height:100%;overflow:auto;border-left:1px solid var(--border);
  padding:10px;background:var(--panel);box-sizing:border-box;z-index:2;backdrop-filter:blur(4px)}
#side h3{margin:4px 0 2px}
#side h4{margin:10px 0 2px;color:var(--muted);font-size:11px;text-transform:uppercase}
#side p{margin:4px 0}
#side ul{margin:4px 0;padding-left:18px}
#side pre{white-space:pre-wrap;background:var(--code);border:1px solid var(--border);padding:6px;
  border-radius:6px;font-size:11px;overflow-x:auto}
#side code{background:var(--code);padding:0 3px;border-radius:3px}
.muted{color:var(--muted)}
.conn{cursor:pointer;padding:2px 4px;border-radius:4px;display:flex;gap:6px;align-items:center}
.conn:hover{background:var(--chip)}
line{stroke:var(--edge-solid)}
line.hl{stroke:var(--hl)}
circle{stroke:var(--bg);stroke-width:.8px;cursor:pointer}
circle.sel{stroke:var(--hl);stroke-width:2.5px}
text{pointer-events:none;font-size:9px;fill:var(--fg);paint-order:stroke;stroke:var(--bg);stroke-width:2.5px}
</style></head><body>
<div id="bar">
  <button id="theme">Light</button>
  <button id="fit">Center tables</button>
  <input id="q" placeholder="search… (id or name)"><span id="meta"></span>
  <div class="row"><span class="rowlab">Kinds</span><span id="kinds" class="chips"></span>
    <span class="mini" data-g="kind" data-v="1">all</span><span class="mini" data-g="kind" data-v="0">none</span></div>
  <div class="row"><span class="rowlab">Domains</span><span id="doms" class="chips"></span>
    <span class="mini" data-g="dom" data-v="1">all</span><span class="mini" data-g="dom" data-v="0">none</span></div>
  <div class="row"><span class="rowlab">Schemas</span><span id="schemas" class="chips"></span>
    <span class="mini" data-g="schema" data-v="1">all</span><span class="mini" data-g="schema" data-v="0">none</span>
    <span class="mini" id="publicApi">public+api</span></div>
</div>
<svg id="svg"></svg><div id="side"></div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/7.8.5/d3.min.js"></script>
<script>
const G = __GRAPH__;
const KCOLOR={table:"#2ea043",view:"#56d4a0",matview:"#56d4a0",enum:"#a78bfa",function:"#f0883e",policy:"#539bf5",trigger:"#d4a72c"};
const TABLELIKE=new Set(["table","view","matview"]);
const SIDEW=320;
document.getElementById("meta").textContent=G.meta.table_count+" tables · "+G.meta.function_count+" fns · "+G.meta.policy_count+" policies · "+G.meta.edge_count+" edges";
const byId={};G.nodes.forEach(n=>byId[n.id]=n);
// adjacency on string ids (built before forceLink mutates edge endpoints into objects)
const adj=new Map();
function addAdj(a,b){if(!adj.has(a))adj.set(a,new Set());adj.get(a).add(b);}
G.edges.forEach(e=>{addAdj(e.source,e.target);addAdj(e.target,e.source);});
// filter state ("families" = node kinds + domains + schemas)
const sortByPriority=(xs,priority=[])=>[...xs].sort((a,b)=>{
  const ia=priority.indexOf(a),ib=priority.indexOf(b);
  if(ia!==-1||ib!==-1)return(ia===-1?999:ia)-(ib===-1?999:ib);
  return String(a).localeCompare(String(b));});
const kinds=sortByPriority(new Set(G.nodes.map(n=>n.kind)),["table","view","matview","enum","function","policy","trigger"]);
const kindCount={};G.nodes.forEach(n=>kindCount[n.kind]=(kindCount[n.kind]||0)+1);
const doms=sortByPriority(new Set(G.nodes.map(n=>n.domain||"unclassified")),
  ["object-core","object-facets","ref-lookups","actor-org","pricing","opening","media","sustainability","rbac","audit","api","other"]);
const domCount={};G.nodes.forEach(n=>{const d=n.domain||"unclassified";domCount[d]=(domCount[d]||0)+1;});
const schemas=sortByPriority(new Set(G.nodes.map(n=>n.schema||"unknown")),
  ["public","api","internal","audit","crm","storage","auth","staging","realtime"]);
const schemaCount={};G.nodes.forEach(n=>{const s=n.schema||"unknown";schemaCount[s]=(schemaCount[s]||0)+1;});
const kindOn=Object.fromEntries(kinds.map(x=>[x,true]));
const domOn=Object.fromEntries(doms.map(x=>[x,true]));
const schemaOn=Object.fromEntries(schemas.map(x=>[x,true]));
let sel=null,q="",zk=1;
const esc=s=>String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
// svg / simulation
const svg=d3.select("#svg"),root=svg.append("g");
const link=root.append("g").selectAll("line").data(G.edges).join("line");
const node=root.append("g").selectAll("circle").data(G.nodes).join("circle")
  .attr("r",d=>d.kind==="table"?7:TABLELIKE.has(d.kind)?6:d.kind==="function"?4.5:d.kind==="enum"?5.5:3)
  .attr("fill",d=>KCOLOR[d.kind]||"#888")
  .on("click",(e,d)=>{e.stopPropagation();select(d);});
const label=root.append("g").selectAll("text").data(G.nodes).join("text").text(d=>d.label).attr("dx",7).attr("dy",3);
const W=Math.max(innerWidth-SIDEW,400),H=innerHeight;
const sim=d3.forceSimulation(G.nodes).force("link",d3.forceLink(G.edges).id(d=>d.id).distance(d=>{
    const sk=d.source.kind,tk=d.target.kind;
    return sk==="policy"||tk==="policy"||sk==="trigger"||tk==="trigger"?28:48;}))
  .force("charge",d3.forceManyBody().strength(d=>TABLELIKE.has(d.kind)?-95:d.kind==="enum"?-75:-42))
  .force("x",d3.forceX(W/2).strength(d=>TABLELIKE.has(d.kind)?0.12:d.kind==="enum"?0.08:0.025))
  .force("y",d3.forceY(H/2).strength(d=>TABLELIKE.has(d.kind)?0.12:d.kind==="enum"?0.08:0.025));
sim.on("tick",()=>{link.attr("x1",d=>d.source.x).attr("y1",d=>d.source.y).attr("x2",d=>d.target.x).attr("y2",d=>d.target.y);
  node.attr("cx",d=>d.x).attr("cy",d=>d.y);label.attr("x",d=>d.x).attr("y",d=>d.y);});
node.call(d3.drag().on("start",(e,d)=>{if(!e.active)sim.alphaTarget(.3).restart();d.fx=d.x;d.fy=d.y;})
  .on("drag",(e,d)=>{d.fx=e.x;d.fy=e.y;}).on("end",(e,d)=>{if(!e.active)sim.alphaTarget(0);d.fx=null;d.fy=null;}));
// zoom & pan; labels for noisy kinds (policy/trigger/function) only appear past the zoom threshold
const ZTHRESH=1.3;
const zoom=d3.zoom().scaleExtent([.08,10]).on("zoom",e=>{
  root.attr("transform",e.transform);
  const big=e.transform.k>=ZTHRESH,wasBig=zk>=ZTHRESH;zk=e.transform.k;
  if(big!==wasBig)refresh();});
svg.call(zoom).on("dblclick.zoom",null);
svg.on("click",()=>{if(sel){sel=null;refresh();sideDefault();}});
// visibility model: filters hide, selection/search dim
const isConn=d=>!!sel&&(d.id===sel.id||(adj.get(sel.id)||new Set()).has(d.id));
const matches=d=>d.id.toLowerCase().includes(q)||d.label.toLowerCase().includes(q);
const visible=n=>kindOn[n.kind]&&domOn[n.domain||"unclassified"]&&schemaOn[n.schema||"unknown"];
function labelShow(d){if(!visible(d))return false;if(sel)return isConn(d);if(q)return matches(d);
  return TABLELIKE.has(d.kind)||d.kind==="enum"||zk>=ZTHRESH;}
function refresh(){
  node.attr("display",d=>visible(d)?null:"none").classed("sel",d=>!!sel&&d.id===sel.id)
    .attr("opacity",d=>sel?(isConn(d)?1:.06):(q?(matches(d)?1:.1):.92));
  label.attr("display",d=>labelShow(d)?null:"none")
    .attr("opacity",d=>sel?(isConn(d)?1:.06):(q?(matches(d)?1:.1):.9));
  link.attr("display",e=>visible(e.source)&&visible(e.target)?null:"none")
    .classed("hl",e=>!!sel&&(e.source.id===sel.id||e.target.id===sel.id))
    .attr("stroke-opacity",e=>{if(sel)return(e.source.id===sel.id||e.target.id===sel.id)?.95:.04;
      if(q)return(matches(e.source)&&matches(e.target))?.5:.06;return .3;})
    .attr("stroke-width",e=>sel&&(e.source.id===sel.id||e.target.id===sel.id)?1.8:1);
}
function select(d){sel=d;refresh();detail(d);}
function selectById(id){const n=byId[id];if(!n)return;select(n);
  svg.transition().duration(450).call(zoom.transform,
    d3.zoomIdentity.translate((innerWidth-SIDEW)/2-n.x*1.4,innerHeight/2-n.y*1.4).scale(1.4));}
function fitVisibleTables(){
  const ns=G.nodes.filter(n=>visible(n)&&TABLELIKE.has(n.kind)&&Number.isFinite(n.x)&&Number.isFinite(n.y));
  if(!ns.length)return;
  const xs=ns.map(n=>n.x),ys=ns.map(n=>n.y),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);
  const vw=Math.max(innerWidth-SIDEW,400),vh=innerHeight,pad=96;
  const bw=Math.max(maxX-minX,40),bh=Math.max(maxY-minY,40);
  const scale=Math.max(.08,Math.min(4,.86*Math.min(vw/(bw+pad),vh/(bh+pad))));
  const tx=vw/2-scale*(minX+maxX)/2,ty=vh/2-scale*(minY+maxY)/2;
  svg.transition().duration(550).call(zoom.transform,d3.zoomIdentity.translate(tx,ty).scale(scale));
}
// side panel
function detail(d){
  let h="<h3>"+esc(d.label)+"</h3><p class=muted>"+esc(d.kind)+" · "+esc(d.schema)+" · "+esc(d.domain)+"</p>";
  if(d.doc)h+="<pre>"+esc(d.doc)+"</pre>";
  if(d.props.columns)h+="<ul>"+d.props.columns.map(c=>"<li><code>"+esc(c.name)+"</code> : "+esc(c.type)+(c.pk?" 🔑":"")+"</li>").join("")+"</ul>";
  if(d.props.signature)h+="<p><code>"+esc(d.props.signature)+" → "+esc(d.props.returns)+"</code></p>";
  if(d.props.values)h+="<p>"+d.props.values.map(esc).join(", ")+"</p>";
  if(d.props.predicate)h+="<pre>"+esc(d.props.predicate)+"</pre>";
  const out={},inn={};
  G.edges.forEach(e=>{const s0=e.source.id||e.source,t0=e.target.id||e.target;
    if(s0===d.id)(out[e.kind]=out[e.kind]||[]).push(t0);
    else if(t0===d.id)(inn[e.kind]=inn[e.kind]||[]).push(s0);});
  const row=id=>{const n2=byId[id];return "<div class=conn data-id=\\""+esc(id)+"\\"><span class=dot style=\\"background:"+(n2?KCOLOR[n2.kind]||"#888":"#888")+"\\"></span>"+esc(n2?n2.label:id)+(n2?" <span class=muted>("+esc(n2.kind)+")</span>":"")+"</div>";};
  const grp=(o,arrow)=>Object.keys(o).sort().map(kk=>"<h4>"+esc(kk)+" "+arrow+" ("+o[kk].length+")</h4>"+o[kk].sort().map(row).join("")).join("");
  const conn=grp(out,"→")+grp(inn,"←");
  if(conn)h+="<h4>Connections</h4>"+conn;
  const s=document.getElementById("side");s.innerHTML=h;s.scrollTop=0;
  s.querySelectorAll(".conn").forEach(el=>el.onclick=()=>selectById(el.dataset.id));
}
function sideDefault(){document.getElementById("side").innerHTML=
  "<h3>DB graph</h3><p class=muted>Click a node to inspect it and highlight its connections. "+
  "Click the background to clear. Scroll to zoom, drag to pan. Use the chips to filter by kind, domain, and schema. "+
  "Labels for functions / policies / triggers appear when zoomed in.</p>";}
// filter chips
function mkChip(parent,name,count,color,get,set){
  const el=document.createElement("span");el.className="chip";
  el.innerHTML=(color?"<span class=dot style=\\"background:"+color+"\\"></span>":"")+esc(name)+" <span class=ct>"+count+"</span>";
  el.onclick=()=>{set(!get());el.classList.toggle("off",!get());refresh();};
  parent.appendChild(el);return el;}
const kindChips={},domChips={},schemaChips={};
kinds.forEach(x=>kindChips[x]=mkChip(document.getElementById("kinds"),x,kindCount[x],KCOLOR[x]||"#888",()=>kindOn[x],v=>kindOn[x]=v));
doms.forEach(x=>domChips[x]=mkChip(document.getElementById("doms"),x,domCount[x],null,()=>domOn[x],v=>domOn[x]=v));
schemas.forEach(x=>schemaChips[x]=mkChip(document.getElementById("schemas"),x,schemaCount[x],null,()=>schemaOn[x],v=>schemaOn[x]=v));
document.querySelectorAll(".mini").forEach(el=>el.onclick=()=>{
  const v=el.dataset.v==="1";
  if(el.dataset.g==="kind"){kinds.forEach(x=>{kindOn[x]=v;kindChips[x].classList.toggle("off",!v);});}
  else if(el.dataset.g==="dom"){doms.forEach(x=>{domOn[x]=v;domChips[x].classList.toggle("off",!v);});}
  else if(el.dataset.g==="schema"){schemas.forEach(x=>{schemaOn[x]=v;schemaChips[x].classList.toggle("off",!v);});}
  refresh();});
document.getElementById("publicApi").onclick=()=>{
  schemas.forEach(x=>{schemaOn[x]=["public","api","internal"].includes(x);schemaChips[x].classList.toggle("off",!schemaOn[x]);});
  refresh();fitVisibleTables();};
// search + theme
document.getElementById("q").addEventListener("input",e=>{q=e.target.value.toLowerCase();refresh();});
document.getElementById("fit").onclick=fitVisibleTables;
const tbtn=document.getElementById("theme");
tbtn.onclick=()=>{const light=document.documentElement.dataset.theme!=="light";
  document.documentElement.dataset.theme=light?"light":"";tbtn.textContent=light?"Dark":"Light";};
refresh();sideDefault();setTimeout(fitVisibleTables,700);
</script></body></html>"""


def render_html(g):
    # "<\\/" parses identically to "</" in a JS string literal but cannot close the <script> tag
    return _HTML.replace("__GRAPH__", json.dumps(g).replace("</", "<\\/"))
