-- ===========================================================================
-- Old_data import - Stage 1 staging load - object_sustainability_action_temp (part 1 of 1)
-- Batch id: old-data-berta2-all-20260501-01
-- Approx size: 24,785 bytes
-- Prerequisite: 00_schema_and_batch.sql has been run.
-- This part holds the DELETE for this table; run before later parts of the same table.
-- ===========================================================================

BEGIN;
DELETE FROM staging.object_sustainability_action_temp WHERE import_batch_id = 'old-data-berta2-all-20260501-01';

INSERT INTO staging.object_sustainability_action_temp (import_batch_id, staging_object_key, action_id, note, source_sheet, raw_source_data, resolution_status, is_approved) VALUES
('old-data-berta2-all-20260501-01', 'c0a466e9', 'MA_EV_CHARGING', U&'borne \00E9lectrique (recharge VTT ou v\00E9hicule)', 'D_Durable', U&'{"ID_D_D":"48b2a9be","Object_id":"c0a466e9","Type_D_D":"borne \00E9lectrique (recharge VTT ou v\00E9hicule)","Commentaire":"","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'recIVYS9o5mvkvjDi', 'MA_ONSITE_COMPOST', U&'prestataire qui utilise les feuilles de palmier pour ses cr\00E9ations', 'D_Durable', U&'{"ID_D_D":"477eddcc","Object_id":"recIVYS9o5mvkvjDi","Type_D_D":"recyclage des v\00E9g\00E9taux","Commentaire":"prestataire qui utilise les feuilles de palmier pour ses cr\00E9ations","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', '59D0EA4483', 'MA_ORGANIC_PRODUCTS', U&'production bio / r\00E9emploi des bocaux usag\00E9s', 'D_Durable', U&'{"ID_D_D":"8cba14d3","Object_id":"59D0EA4483","Type_D_D":"Produits labellis\00E9s bio","Commentaire":"production bio / r\00E9emploi des bocaux usag\00E9s","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'recjVuOypOyayuqqy', 'MA_ONTRIP_BRIEFING', U&'visites guid\00E9es', 'D_Durable', U&'{"ID_D_D":"7b6c96ab","Object_id":"recjVuOypOyayuqqy","Type_D_D":"Sensibilisation de la client\00E8le","Commentaire":"visites guid\00E9es","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'recjVuOypOyayuqqy', 'MA_ORGANIC_PRODUCTS', U&'Produits labellis\00E9s bio', 'D_Durable', U&'{"ID_D_D":"8ed47988","Object_id":"recjVuOypOyayuqqy","Type_D_D":"Produits labellis\00E9s bio","Commentaire":"","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'recEqFurEd2CSBjqg', 'MA_COMMON_BINS', U&'composteur / tri des d\00E9chets', 'D_Durable', U&'{"ID_D_D":"70d472f0","Object_id":"recEqFurEd2CSBjqg","Type_D_D":"Gestion des d\00E9chets","Commentaire":"composteur / tri des d\00E9chets","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'recfcEj0VScC9avif', 'MA_COMMON_BINS', U&'composteur / tri des d\00E9chets', 'D_Durable', U&'{"ID_D_D":"82bee9a0","Object_id":"recfcEj0VScC9avif","Type_D_D":"Gestion des d\00E9chets","Commentaire":"composteur / tri des d\00E9chets","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', '3e9ccb68', 'MA_COMMON_BINS', U&'composteur / tri des d\00E9chets', 'D_Durable', U&'{"ID_D_D":"1b9487d1","Object_id":"3e9ccb68","Type_D_D":"Gestion des d\00E9chets","Commentaire":"composteur / tri des d\00E9chets","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'rec9VUy4xPzBe6RkX', 'MA_ONTRIP_BRIEFING', 'fermette biologique / utilisation de produits bio', 'D_Durable', U&'{"ID_D_D":"27cf440f","Object_id":"rec9VUy4xPzBe6RkX","Type_D_D":"Sensibilisation de la client\00E8le","Commentaire":"fermette biologique / utilisation de produits bio","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'rec9VUy4xPzBe6RkX', 'MA_MONTHLY_ENERGY_READING', U&'Panneaux photovolta\00EFques', 'D_Durable', U&'{"ID_D_D":"40fd8f03","Object_id":"rec9VUy4xPzBe6RkX","Type_D_D":"Gestion de l''\00E9nergie","Commentaire":"Panneaux photovolta\00EFques","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'rec9VUy4xPzBe6RkX', 'MA_COMMON_BINS', U&'tri des d\00E9chets', 'D_Durable', U&'{"ID_D_D":"70784837","Object_id":"rec9VUy4xPzBe6RkX","Type_D_D":"Gestion des d\00E9chets","Commentaire":"tri des d\00E9chets","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'rec9VUy4xPzBe6RkX', 'MA_WATER_READING', U&'R\00E9cup\00E9ration de l''eau de pluie', 'D_Durable', U&'{"ID_D_D":"fe3de992","Object_id":"rec9VUy4xPzBe6RkX","Type_D_D":"Gestion de l''eau","Commentaire":"R\00E9cup\00E9ration de l''eau de pluie","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'recv9dk9YRWpnfk4H', 'MA_COMMON_BINS', U&'Tri s\00E9lectif', 'D_Durable', U&'{"ID_D_D":"30ab42af","Object_id":"recv9dk9YRWpnfk4H","Type_D_D":"Gestion des d\00E9chets","Commentaire":"Tri s\00E9lectif","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'recv9dk9YRWpnfk4H', 'MA_MONTHLY_ENERGY_READING', 'Chauffe-eau solaire', 'D_Durable', U&'{"ID_D_D":"982abb03","Object_id":"recv9dk9YRWpnfk4H","Type_D_D":"Gestion de l''\00E9nergie","Commentaire":"Chauffe-eau solaire","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'recv9dk9YRWpnfk4H', 'MA_ONTRIP_BRIEFING', U&'Sensibilisation de la client\00E8le', 'D_Durable', U&'{"ID_D_D":"8a62b7e2","Object_id":"recv9dk9YRWpnfk4H","Type_D_D":"Sensibilisation de la client\00E8le","Commentaire":"","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'recOk422JMgj9tU8L', 'MA_MONTHLY_ENERGY_READING', 'Eclairage LED / chauffe-eau solaire', 'D_Durable', U&'{"ID_D_D":"85363fa8","Object_id":"recOk422JMgj9tU8L","Type_D_D":"Gestion de l''\00E9nergie","Commentaire":"Eclairage LED / chauffe-eau solaire","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'recOk422JMgj9tU8L', 'MA_COMMON_BINS', U&'Tri s\00E9lectif', 'D_Durable', U&'{"ID_D_D":"499a3b77","Object_id":"recOk422JMgj9tU8L","Type_D_D":"Gestion des d\00E9chets","Commentaire":"Tri s\00E9lectif","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'recOk422JMgj9tU8L', 'MA_WATERLESS_URINALS', U&'Phyto-\00E9puration', 'D_Durable', U&'{"ID_D_D":"e9ae000f","Object_id":"recOk422JMgj9tU8L","Type_D_D":"Assainissement Durable","Commentaire":"Phyto-\00E9puration","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'recOk422JMgj9tU8L', 'MA_WATER_READING', U&'r\00E9cup\00E9ration de l''eau de pluie', 'D_Durable', U&'{"ID_D_D":"09dbd670","Object_id":"recOk422JMgj9tU8L","Type_D_D":"Gestion de l''eau","Commentaire":"r\00E9cup\00E9ration de l''eau de pluie","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'recOk422JMgj9tU8L', 'MA_ONTRIP_BRIEFING', 'mini ferme / accessible aux PMR et autres types de handicaps', 'D_Durable', U&'{"ID_D_D":"e23bef1d","Object_id":"recOk422JMgj9tU8L","Type_D_D":"Sensibilisation de la client\00E8le","Commentaire":"mini ferme / accessible aux PMR et autres types de handicaps","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'rec5Xr38CzqCc6d1f', 'MA_BIODIVERSITY_AWARENESS', U&'lutte contre les esp\00E8ces envahissantes / arboretum d''esp\00E8ces end\00E9miques et indig\00E8nes', 'D_Durable', U&'{"ID_D_D":"05b85640","Object_id":"rec5Xr38CzqCc6d1f","Type_D_D":"Pr\00E9servation de la biodiversit\00E9","Commentaire":"lutte contre les esp\00E8ces envahissantes / arboretum d''esp\00E8ces end\00E9miques et indig\00E8nes","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'rec5Xr38CzqCc6d1f', 'MA_COMMON_BINS', U&'tri / orientation z\00E9ro d\00E9chets', 'D_Durable', U&'{"ID_D_D":"6c2bfabb","Object_id":"rec5Xr38CzqCc6d1f","Type_D_D":"Gestion des d\00E9chets","Commentaire":"tri / orientation z\00E9ro d\00E9chets","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'rec5Xr38CzqCc6d1f', 'MA_MONTHLY_ENERGY_READING', U&'Autonomie \00E9nerg\00E9tique / panneaux photovolta\00EFques', 'D_Durable', U&'{"ID_D_D":"14edf03d","Object_id":"rec5Xr38CzqCc6d1f","Type_D_D":"Gestion de l''\00E9nergie","Commentaire":"Autonomie \00E9nerg\00E9tique / panneaux photovolta\00EFques","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'rec5Xr38CzqCc6d1f', 'MA_WATERLESS_URINALS', U&'Toilettes s\00E8ches', 'D_Durable', U&'{"ID_D_D":"120b383b","Object_id":"rec5Xr38CzqCc6d1f","Type_D_D":"Assainissement Durable","Commentaire":"Toilettes s\00E8ches","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'rec5Xr38CzqCc6d1f', 'MA_WATER_READING', U&'R\00E9cup\00E9ration de l''eau de pluie', 'D_Durable', U&'{"ID_D_D":"a35eb637","Object_id":"rec5Xr38CzqCc6d1f","Type_D_D":"Gestion de l''eau","Commentaire":"R\00E9cup\00E9ration de l''eau de pluie","source_system":"berta_v2_csv_export"}', 'review_required', 'false');
INSERT INTO staging.object_sustainability_action_temp (import_batch_id, staging_object_key, action_id, note, source_sheet, raw_source_data, resolution_status, is_approved) VALUES
('old-data-berta2-all-20260501-01', '96b0af71', 'MA_ORGANIC_PRODUCTS', 'Cuisine avec pdts bio et locaux', 'D_Durable', U&'{"ID_D_D":"c2851993","Object_id":"96b0af71","Type_D_D":"Produits labellis\00E9s bio","Commentaire":"Cuisine avec pdts bio et locaux","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', '96b0af71', 'MA_COMMON_BINS', U&'Tri effectu\00E9 par les h\00E9bergeurs', 'D_Durable', U&'{"ID_D_D":"ce641f36","Object_id":"96b0af71","Type_D_D":"Gestion des d\00E9chets","Commentaire":"Tri effectu\00E9 par les h\00E9bergeurs","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', '96b0af71', 'MA_MONTHLY_ENERGY_READING', U&'\00C9clairage LED et solaire', 'D_Durable', U&'{"ID_D_D":"2d46430d","Object_id":"96b0af71","Type_D_D":"Gestion de l''\00E9nergie","Commentaire":"\00C9clairage LED et solaire","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', '96b0af71', 'MA_WATER_READING', 'Recuperation eau de pluie une citerne pr le jardin, piscine, jacuzzi', 'D_Durable', '{"ID_D_D":"8af361f6","Object_id":"96b0af71","Type_D_D":"Gestion de l''eau","Commentaire":"Recuperation eau de pluie une citerne pr le jardin, piscine, jacuzzi","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'rec5vqdPwSdrFzsvs', 'MA_COMMON_BINS', U&'Tri des d\00E9chets propos\00E9 aux clients.', 'D_Durable', U&'{"ID_D_D":"5d1878cd","Object_id":"rec5vqdPwSdrFzsvs","Type_D_D":"Gestion des d\00E9chets","Commentaire":"Tri des d\00E9chets propos\00E9 aux clients.","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'rec5vqdPwSdrFzsvs', 'MA_WATER_READING', U&'L\2019h\00F4tel est \00E9quip\00E9 des \00E9quipements sanitaires les plus r\00E9cents, incluant notamment des mousseurs et des robinets avec cran \00E9conomiseur d\2019eau \00E0 double position, qui permettent de limiter le d\00E9bit et donc la consommation. Les WC sont \00E9quip\00E9s de la m\00EAme mani\00E8re de chasse-d \2019eau \00E0 double poussoir.', 'D_Durable', U&'{"ID_D_D":"c8cde98a","Object_id":"rec5vqdPwSdrFzsvs","Type_D_D":"Gestion de l''eau","Commentaire":"L\2019h\00F4tel est \00E9quip\00E9 des \00E9quipements sanitaires les plus r\00E9cents, incluant notamment des mousseurs et des robinets avec cran \00E9conomiseur d\2019eau \00E0 double position, qui permettent de limiter le d\00E9bit et donc la consommation. Les WC sont \00E9quip\00E9s de la m\00EAme mani\00E8re de chasse-d \2019eau \00E0 double poussoir.","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'rec5vqdPwSdrFzsvs', 'MA_MONTHLY_ENERGY_READING', U&'R\00E9duction de la consommation \00E9lectrique (pas de t\00E9l\00E9vision dans les chambres, \00E9clairage ext\00E9rieur avec d\00E9tecteur de pr\00E9sence)', 'D_Durable', U&'{"ID_D_D":"d53322b2","Object_id":"rec5vqdPwSdrFzsvs","Type_D_D":"Gestion de l''\00E9nergie","Commentaire":"R\00E9duction de la consommation \00E9lectrique (pas de t\00E9l\00E9vision dans les chambres, \00E9clairage ext\00E9rieur avec d\00E9tecteur de pr\00E9sence)","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'rec5vqdPwSdrFzsvs', 'MA_BIODIVERSITY_AWARENESS', U&'Le v\00E9g\00E9tal fait partie int\00E9grante de la strat\00E9gie environnementale du projet du Dimitile. Le projet paysager met en valeur les esp\00E8ces end\00E9miques et la biodiversit\00E9 du site : les plus gros sujets ont d\2019ailleurs \00E9t\00E9 d\00E9plant\00E9s, mis en nourrice, puis replant\00E9s \00E0 l\2019issue des travaux.', 'D_Durable', U&'{"ID_D_D":"f80621a1","Object_id":"rec5vqdPwSdrFzsvs","Type_D_D":"Pr\00E9servation de la biodiversit\00E9","Commentaire":"Le v\00E9g\00E9tal fait partie int\00E9grante de la strat\00E9gie environnementale du projet du Dimitile. Le projet paysager met en valeur les esp\00E8ces end\00E9miques et la biodiversit\00E9 du site : les plus gros sujets ont d\2019ailleurs \00E9t\00E9 d\00E9plant\00E9s, mis en nourrice, puis replant\00E9s \00E0 l\2019issue des travaux.","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', '022C4A9B1C', 'MA_COMMON_BINS', U&'Suppression des consommables \00E0 usage unique et l\2019\00E9limination des emballages plastiques.', 'D_Durable', U&'{"ID_D_D":"2f23e26f","Object_id":"022C4A9B1C","Type_D_D":"Gestion des d\00E9chets","Commentaire":"Suppression des consommables \00E0 usage unique et l\2019\00E9limination des emballages plastiques.","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', '022C4A9B1C', 'MA_LOCAL_SUPPLIER_LIST', U&'Le restaurant du Dimitile souhaite promouvoir le savoir-faire et l\2019agriculture de l\2019\00EEle en privil\00E9giant les fruits et l\00E9gumes locaux et de saison. Les mara\00EEchers sont s\00E9lectionn\00E9s pour la qualit\00E9 de leurs produits et l\2019utilisation limit\00E9e de pesticides dans leurs exploitations.', 'D_Durable', U&'{"ID_D_D":"1ca44c32","Object_id":"022C4A9B1C","Type_D_D":"Produits en circuit court","Commentaire":"Le restaurant du Dimitile souhaite promouvoir le savoir-faire et l\2019agriculture de l\2019\00EEle en privil\00E9giant les fruits et l\00E9gumes locaux et de saison. Les mara\00EEchers sont s\00E9lectionn\00E9s pour la qualit\00E9 de leurs produits et l\2019utilisation limit\00E9e de pesticides dans leurs exploitations.","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'rec5vqdPwSdrFzsvs', NULL, U&'Les b\00E2timents du Dimitile ont \00E9t\00E9 con\00E7u en int\00E9grant les grands principes bioclimatiques : orientation des \00E9difices, utilisation de voiles d\2019ombrages ou dimensionnement des d\00E9bords de toit pour g\00E9rer au mieux les apports solaires en les favorisant lors de la saison fra\00EEche et en s\2019en prot\00E9geant lors de la saison chaude.', 'D_Durable', U&'{"ID_D_D":"84c40691","Object_id":"rec5vqdPwSdrFzsvs","Type_D_D":"Construction bioclimatique","Commentaire":"Les b\00E2timents du Dimitile ont \00E9t\00E9 con\00E7u en int\00E9grant les grands principes bioclimatiques : orientation des \00E9difices, utilisation de voiles d\2019ombrages ou dimensionnement des d\00E9bords de toit pour g\00E9rer au mieux les apports solaires en les favorisant lors de la saison fra\00EEche et en s\2019en prot\00E9geant lors de la saison chaude.","source_system":"berta_v2_csv_export"}', 'rejected', 'false'),
('old-data-berta2-all-20260501-01', 'rec5vqdPwSdrFzsvs', NULL, U&'Formation du personnel aux pratiques \00E9coresponsables (formation obligatoire d\00E9marche \00E9co responsable dans une entreprise).', 'D_Durable', U&'{"ID_D_D":"9dc593d0","Object_id":"rec5vqdPwSdrFzsvs","Type_D_D":"Sensibilisation du personnel","Commentaire":"Formation du personnel aux pratiques \00E9coresponsables (formation obligatoire d\00E9marche \00E9co responsable dans une entreprise).","source_system":"berta_v2_csv_export"}', 'rejected', 'false'),
('old-data-berta2-all-20260501-01', 'rec5vqdPwSdrFzsvs', NULL, U&'Le groupe AMANTA, dont fait partie Le Dimitile, est membre du mouvement 1% pour la plan\00E8te et reverse ainsi 1% de son chiffre d\2019affaires \00E0 des fins environnementales.', 'D_Durable', U&'{"ID_D_D":"341fee0c","Object_id":"rec5vqdPwSdrFzsvs","Type_D_D":"Soutien associatif","Commentaire":"Le groupe AMANTA, dont fait partie Le Dimitile, est membre du mouvement 1% pour la plan\00E8te et reverse ainsi 1% de son chiffre d\2019affaires \00E0 des fins environnementales.","source_system":"berta_v2_csv_export"}', 'rejected', 'false'),
('old-data-berta2-all-20260501-01', '022C4A9B1C', NULL, U&'Le groupe AMANTA, dont fait partie Le Dimitile, est membre du mouvement 1% pour la plan\00E8te et reverse ainsi 1% de son chiffre d\2019affaires \00E0 des fins environnementales.', 'D_Durable', U&'{"ID_D_D":"bad6635c","Object_id":"022C4A9B1C","Type_D_D":"Soutien associatif","Commentaire":"Le groupe AMANTA, dont fait partie Le Dimitile, est membre du mouvement 1% pour la plan\00E8te et reverse ainsi 1% de son chiffre d\2019affaires \00E0 des fins environnementales.","source_system":"berta_v2_csv_export"}', 'rejected', 'false'),
('old-data-berta2-all-20260501-01', '97c59f68', 'MA_WATER_READING', U&'L\2019h\00F4tel utilise des \00E9quipements sanitaires \00E9conomes en eau et une couverture automatique pour la piscine afin de limiter les pertes thermiques et l\2019\00E9vaporation. Le chauffage de la piscine est assur\00E9 par une pompe \00E0 chaleur.', 'D_Durable', U&'{"ID_D_D":"795cf17d","Object_id":"97c59f68","Type_D_D":"Gestion de l''eau","Commentaire":"L\2019h\00F4tel utilise des \00E9quipements sanitaires \00E9conomes en eau et une couverture automatique pour la piscine afin de limiter les pertes thermiques et l\2019\00E9vaporation. Le chauffage de la piscine est assur\00E9 par une pompe \00E0 chaleur.","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'recd0bjcfRVLbyOCv', 'MA_EV_CHARGING', U&'borne \00E9lectrique (recharge VTT ou v\00E9hicule)', 'D_Durable', U&'{"ID_D_D":"8150c3bc","Object_id":"recd0bjcfRVLbyOCv","Type_D_D":"borne \00E9lectrique (recharge VTT ou v\00E9hicule)","Commentaire":"","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'recd0bjcfRVLbyOCv', 'MA_COMMON_BINS', 'Composte, panier gourmand anti-gaspillage', 'D_Durable', U&'{"ID_D_D":"fd789863","Object_id":"recd0bjcfRVLbyOCv","Type_D_D":"Gestion des d\00E9chets","Commentaire":"Composte, panier gourmand anti-gaspillage","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'recd0bjcfRVLbyOCv', 'MA_MONTHLY_ENERGY_READING', U&'Chauffe-Eau Solaire, \00E9clairage ext\00E9rieur solaire et led dans l''h\00F4tel', 'D_Durable', U&'{"ID_D_D":"e975ad12","Object_id":"recd0bjcfRVLbyOCv","Type_D_D":"Gestion de l''\00E9nergie","Commentaire":"Chauffe-Eau Solaire, \00E9clairage ext\00E9rieur solaire et led dans l''h\00F4tel","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', '99434ac2', 'MA_FURNITURE_REUSE', 'Recyclage de papier', 'D_Durable', '{"ID_D_D":"65f9f55d","Object_id":"99434ac2","Type_D_D":"Upcycling","Commentaire":"Recyclage de papier","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', '38bee07f', 'MA_MONTHLY_ENERGY_READING', 'Chauffe-eau solaire', 'D_Durable', U&'{"ID_D_D":"12fdbe56","Object_id":"38bee07f","Type_D_D":"Gestion de l''\00E9nergie","Commentaire":"Chauffe-eau solaire","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', '38bee07f', 'MA_COMMON_BINS', U&'Tri s\00E9lectif', 'D_Durable', U&'{"ID_D_D":"3e7cae51","Object_id":"38bee07f","Type_D_D":"Gestion des d\00E9chets","Commentaire":"Tri s\00E9lectif","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', '9a8f7c6d', 'MA_COMMON_BINS', U&'Compostage et poulailler (d\00E9chets alimentaires)', 'D_Durable', U&'{"ID_D_D":"06ba2d88","Object_id":"9a8f7c6d","Type_D_D":"Gestion des d\00E9chets","Commentaire":"Compostage et poulailler (d\00E9chets alimentaires)","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', '9a8f7c6d', 'MA_COMMON_BINS', U&'Tri s\00E9lectif', 'D_Durable', U&'{"ID_D_D":"61d500c5","Object_id":"9a8f7c6d","Type_D_D":"Gestion des d\00E9chets","Commentaire":"Tri s\00E9lectif","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', '9a8f7c6d', 'MA_ONSITE_COMPOST', 'compostage', 'D_Durable', U&'{"ID_D_D":"e34d56c9","Object_id":"9a8f7c6d","Type_D_D":"recyclage des v\00E9g\00E9taux","Commentaire":"compostage","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', '9a8f7c6d', 'MA_LOCAL_SUPPLIER_LIST', U&'choix de fournisseurs locaux d\00E8s que possible et produits p\00E9i', 'D_Durable', U&'{"ID_D_D":"0abb4bd6","Object_id":"9a8f7c6d","Type_D_D":"Produits en circuit court","Commentaire":"choix de fournisseurs locaux d\00E8s que possible et produits p\00E9i","source_system":"berta_v2_csv_export"}', 'review_required', 'false');
INSERT INTO staging.object_sustainability_action_temp (import_batch_id, staging_object_key, action_id, note, source_sheet, raw_source_data, resolution_status, is_approved) VALUES
('old-data-berta2-all-20260501-01', '38bee07f', 'MA_ONSITE_COMPOST', 'compostage', 'D_Durable', U&'{"ID_D_D":"6fc4568f","Object_id":"38bee07f","Type_D_D":"recyclage des v\00E9g\00E9taux","Commentaire":"compostage","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'a311fc46', 'MA_COMMON_BINS', U&'Tri des d\00E9chets disponible dans la maison : compost, verre, poubelle jaune', 'D_Durable', U&'{"ID_D_D":"41884c4e","Object_id":"a311fc46","Type_D_D":"Gestion des d\00E9chets","Commentaire":"Tri des d\00E9chets disponible dans la maison : compost, verre, poubelle jaune","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'a311fc46', 'MA_ONTRIP_BRIEFING', U&'dispose d''un livret d''accueil avec des \00E9l\00E9ments de sensibilisation \00E0 la protection de l''environnement', 'D_Durable', U&'{"ID_D_D":"b8723b14","Object_id":"a311fc46","Type_D_D":"Sensibilisation de la client\00E8le","Commentaire":"dispose d''un livret d''accueil avec des \00E9l\00E9ments de sensibilisation \00E0 la protection de l''environnement","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'a311fc46', 'MA_MONTHLY_ENERGY_READING', U&'Panneaux photovolta\00EFque et chauffe eau solaire', 'D_Durable', U&'{"ID_D_D":"f96edc5e","Object_id":"a311fc46","Type_D_D":"Gestion de l''\00E9nergie","Commentaire":"Panneaux photovolta\00EFque et chauffe eau solaire","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'a311fc46', 'MA_WATER_READING', U&'R\00E9cup\00E9ration de l''eau de pluie pour le jardin, chasse d''eau \00E9co, cuisine \00E9quip\00E9e de robinet \00E0 double d\00E9bit', 'D_Durable', U&'{"ID_D_D":"d0ba7bc0","Object_id":"a311fc46","Type_D_D":"Gestion de l''eau","Commentaire":"R\00E9cup\00E9ration de l''eau de pluie pour le jardin, chasse d''eau \00E9co, cuisine \00E9quip\00E9e de robinet \00E0 double d\00E9bit","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'a311fc46', 'MA_ORGANIC_PRODUCTS', U&'Produits bio \00E0 dispo des clients : produit vaisselle et lave-vaisselle, produits m\00E9nagers, savon bio', 'D_Durable', U&'{"ID_D_D":"5fcedc8d","Object_id":"a311fc46","Type_D_D":"Produits labellis\00E9s bio","Commentaire":"Produits bio \00E0 dispo des clients : produit vaisselle et lave-vaisselle, produits m\00E9nagers, savon bio","source_system":"berta_v2_csv_export"}', 'review_required', 'false'),
('old-data-berta2-all-20260501-01', 'a311fc46', 'MA_MONTHLY_ENERGY_READING', 'Pas de climatiseurs, la structure dispose de brasseurs d''air', 'D_Durable', U&'{"ID_D_D":"54b9c9ab","Object_id":"a311fc46","Type_D_D":"Gestion de l''\00E9nergie","Commentaire":"Pas de climatiseurs, la structure dispose de brasseurs d''air","source_system":"berta_v2_csv_export"}', 'review_required', 'false');
COMMIT;
