import type { ObjectWorkspacePermissions } from '../../../services/object-workspace';
import type { ObjectWorkspaceModules, WorkspaceTranslatableField } from '../../../services/object-workspace-parser';

function tf(value: string): WorkspaceTranslatableField {
  return { baseValue: value, values: { fr: value } };
}

export const allowAll = new Proxy(
  {},
  {
    get: () => ({
      canDirectWrite: true,
      canPrepareProposal: true,
      canSubmitProposal: true,
      disabledReason: null,
      canEditPlaceDescriptions: true,
      canEditPlaceMedia: true,
      canEditPlaces: true,
      canEditZones: true,
    }),
  },
) as ObjectWorkspacePermissions;

export function fullModulesFixture(): ObjectWorkspaceModules {
  return {
    generalInfo: {
      name: 'Domaine du Bel Air',
      nameTranslations: {},
      businessTimezone: 'Indian/Reunion',
      commercialVisibility: 'active',
      regionCode: 'RE',
      status: 'published',
      publishedAt: '2026-01-02',
      isEditing: true,
      secondaryTypes: [],
    },
    taxonomy: { domains: [], unavailableReason: null },
    descriptions: {
      localLanguage: 'fr',
      activeLanguage: 'fr',
      availableLanguages: ['fr', 'en'],
      object: {
        recordId: 'd1',
        scope: 'object',
        placeId: null,
        label: 'Objet',
        visibility: 'public',
        description: tf('Description principale'),
        chapo: tf('Chapo'),
        adaptedDescription: tf('Adaptée'),
        mobileDescription: tf('Mobile'),
        editorialDescription: tf('Editoriale'),
      },
      orgOverlay: null,
      places: [
        {
          recordId: 'pd1',
          scope: 'place',
          placeId: 'p1',
          label: 'Belvédère',
          visibility: 'public',
          description: tf('Vue sur le cirque'),
          chapo: tf(''),
          adaptedDescription: tf(''),
          mobileDescription: tf(''),
          editorialDescription: tf(''),
        },
      ],
    },
    location: {
      main: {
        recordId: 'l1',
        address1: '1 rue du Test',
        address1Suite: '',
        address2: '',
        address3: '',
        postcode: '97410',
        city: 'Saint-Pierre',
        codeInsee: '',
        lieuDit: '',
        direction: '',
        latitude: '-21.3',
        longitude: '55.4',
        zoneTouristique: 'Sud',
      },
      places: [],
      zoneCodes: ['97422'],
      zoneOptions: [
        { code: '97422', label: 'Le Tampon' },
        { code: '97412', label: 'Saint-Joseph' },
      ],
      zonesUnavailableReason: null,
    },
    contacts: {
      objectItems: [
        {
          id: 'c1',
          kindId: 'k1',
          kindCode: 'phone',
          kindLabel: 'Téléphone',
          roleId: '',
          roleCode: '',
          roleLabel: '',
          value: '+262 000',
          isPublic: true,
          isPrimary: true,
          position: '0',
        },
      ],
      kindOptions: [
        { id: 'k1', code: 'phone', label: 'Téléphone' },
        { id: 'k2', code: 'email', label: 'E-mail' },
      ],
      roleOptions: [
        { id: 'r1', code: 'accueil', label: 'Accueil' },
        { id: 'r2', code: 'reservation', label: 'Réservation' },
      ],
      webItems: [],
      webKindOptions: [
        { id: 'wk1', code: 'facebook', label: 'Facebook' },
        { id: 'wk2', code: 'instagram', label: 'Instagram' },
        { id: 'wk3', code: 'booking', label: 'Booking.com' },
      ],
      relatedActorContactsCount: 0,
      relatedOrganizationContactsCount: 0,
    },
    media: {
      // Real ref_code media_type codes (seeds_data.sql) — fictional codes would
      // dodge the authorable-type filter the section applies.
      typeOptions: [
        { id: 'mt1', code: 'photo', label: 'Photo' },
        { id: 'mt2', code: 'brochure_pdf', label: 'Brochure PDF' },
      ],
      tagOptions: [],
      objectItems: [
        {
          id: 'm1',
          scope: 'object',
          placeId: null,
          scopeLabel: 'Objet',
          typeId: 'mt1',
          typeCode: 'photo',
          typeLabel: 'Photo',
          title: 'Hero image',
          titleTranslations: {},
          description: 'Façade',
          descriptionTranslations: {},
          // A DB media row always has a URL (chk_media_url_not_empty) — an empty url
          // would trip the modal's honest save guard and make the fixture unrealistic.
          url: 'https://cdn.example/hero.jpg',
          credit: '',
          visibility: 'public',
          position: '0',
          width: '',
          height: '',
          rightsExpiresAt: '',
          kind: 'image',
          isMain: true,
          isPublished: true,
          tags: [],
        },
      ],
      placeItems: [],
      placeScopeUnavailableReason: null,
      unavailableReason: null,
    },
    characteristics: {
      languageOptions: [{ id: 'fr', code: 'fr', label: 'Français' }, { id: 'en', code: 'en', label: 'Anglais' }],
      languageLevelOptions: [{ id: 'native', code: 'native', label: 'Courant' }],
      selectedLanguages: [{ languageId: 'fr', code: 'fr', label: 'Français', levelId: 'native', levelCode: 'native', levelLabel: 'Courant' }],
      paymentOptions: [{ id: 'card', code: 'card', label: 'CB' }, { id: 'cash', code: 'cash', label: 'Espèces' }],
      selectedPaymentCodes: ['card'],
      environmentOptions: [{ id: 'garden', code: 'garden', label: 'Jardin' }],
      selectedEnvironmentCodes: [],
      amenityGroups: [
        { familyCode: 'accessibility', familyLabel: 'Accessibilité', options: [{ id: 'pmr', code: 'pmr_access', label: 'Accès PMR', disabilityTypes: ['motor'] }] },
        { familyCode: 'services', familyLabel: 'Services', options: [{ id: 'wifi', code: 'wifi', label: 'Wi-Fi', disabilityTypes: [] }] },
      ],
      selectedAmenityCodes: ['wifi'],
      unavailableReason: null,
    },
    capacityPolicies: {
      // Real ref_capacity_metric code — the old fictional 'capacity_total' let the §06→§07
      // sync tests pass while the sync was a silent no-op against the live catalog.
      metricOptions: [{ id: 'cap', code: 'max_capacity', label: 'Capacité max.' }],
      capacityItems: [{ recordId: 'cap1', metricId: 'cap', metricCode: 'max_capacity', metricLabel: 'Capacité max.', unit: 'pax', value: '48', effectiveFrom: '', effectiveTo: '' }],
      groupPolicy: { minSize: '8', maxSize: '40', groupOnly: false, notes: 'Sur réservation' },
      petPolicy: { accepted: false, conditions: 'Petits animaux' },
      stayPolicy: { checkInFrom: '16:00', checkInUntil: '20:00', checkOutUntil: '11:00', conditions: 'Arrivée tardive sur demande' },
      unavailableReason: null,
    },
    distinctions: {
      distinctionGroups: [
        {
          schemeCode: 'stars',
          schemeLabel: 'Étoiles',
          items: [{ recordId: 'di1', schemeId: 'stars', schemeCode: 'stars', schemeLabel: 'Étoiles', valueId: '4', valueCode: '4', valueLabel: '4 étoiles', status: 'granted', awardedAt: '2025-01-01', validUntil: '', disabilityTypesCovered: [], documentId: '', documentUrl: '', documentTitle: '' }],
        },
      ],
      accessibilityLabels: [{ recordId: 'acc1', schemeId: 'acc', schemeCode: 'acc', schemeLabel: 'Accessibilité', valueId: 'pmr', valueCode: 'pmr', valueLabel: 'Tourisme Handicap', status: 'granted', awardedAt: '', validUntil: '', disabilityTypesCovered: ['motor'], documentId: '', documentUrl: '', documentTitle: '' }],
      accessibilityAmenityCoverage: [{ code: 'pmr_access', label: 'Accès PMR', disabilityTypes: ['motor'] }],
      schemeOptions: [],
      unavailableReason: null,
    },
    pricing: {
      priceKindOptions: [{ id: 'adult', code: 'adult', label: 'Adulte' }, { id: 'enfant', code: 'enfant', label: 'Enfant' }],
      priceTypeOptions: [{ id: 'principal', code: 'principal', label: 'Tarif principal' }, { id: 'option', code: 'option', label: 'Option / extra' }],
      priceSeasonOptions: [{ id: 'high_season', code: 'high_season', label: 'Haute saison' }, { id: 'low_season', code: 'low_season', label: 'Basse saison' }],
      priceUnitOptions: [{ id: 'person', code: 'person', label: 'Par personne' }, { id: 'nuit', code: 'nuit', label: 'Par nuit' }],
      prices: [{ recordId: 'pr1', kindId: 'adult', kindCode: 'adult', kindLabel: 'Adulte', unitId: 'person', unitCode: 'person', unitLabel: 'Par personne', amount: '12', amountMax: '', currency: 'EUR', seasonCode: '', indicationCode: 'principal', ageMinEnfant: '', ageMaxEnfant: '', ageMinJunior: '', ageMaxJunior: '', validFrom: '', validTo: '', conditions: '', source: '', periods: [] }],
      discounts: [],
      promotions: [],
      promotionsUnavailableReason: null,
      unavailableReason: null,
    },
    rooms: {
      viewTypeOptions: [],
      roomTypeOptions: [{ id: 'rt1', code: 'double', label: 'Chambre double' }],
      amenityOptions: [{ id: 'wifi', code: 'wifi', label: 'Wi-Fi' }],
      amenityGroups: [{ familyCode: 'general', familyLabel: 'Général', options: [{ id: 'wifi', code: 'wifi', label: 'Wi-Fi', disabilityTypes: [] }] }],
      bedTypeOptions: [{ id: 'bt1', code: 'double', label: 'Lit double (140 cm)' }],
      mediaOptions: [],
      items: [{ recordId: 'r1', code: 'std', name: 'Chambre standard', nameTranslations: {}, description: '', descriptionTranslations: {}, capacityAdults: '2', capacityChildren: '0', capacityTotal: '2', sizeSqm: '22', bedConfig: 'Double', bedConfigTranslations: {}, quantity: '12', floorLevel: '', viewTypeId: '', viewTypeCode: '', viewTypeLabel: '', roomTypeId: 'rt1', roomTypeCode: 'double', roomTypeLabel: 'Chambre double', basePrice: '165', currency: 'EUR', accessible: false, published: true, position: '1', amenityCodes: ['wifi'], mediaIds: [], beds: [] }],
      unavailableReason: null,
    },
    meetingRooms: {
      equipmentOptions: [],
      items: [{ recordId: 'mr1', name: 'Salle Bras-Long', nameTranslations: {}, areaM2: '78', capacityTheatre: '60', capacityU: '32', capacityClassroom: '32', capacityBoardroom: '20', equipmentCodes: [] }],
      unavailableReason: null,
    },
    menus: {
      categoryOptions: [{ id: 'carte', code: 'carte', label: 'Carte' }],
      dietaryTagOptions: [],
      allergenOptions: [],
      cuisineTypeOptions: [{ id: 'creole', code: 'creole', label: 'Créole' }],
      priceKindOptions: [{ id: 'dish', code: 'dish', label: 'Plat' }],
      priceUnitOptions: [{ id: 'unit', code: 'unit', label: 'Unité' }],
      mediaOptions: [],
      items: [{ recordId: 'menu1', categoryId: 'carte', categoryCode: 'carte', categoryLabel: 'Carte', name: 'Carte midi', description: '', active: true, visibility: 'public', position: '1', items: [{ recordId: 'mi1', name: 'Cari', description: '', price: '18', currency: 'EUR', kindId: 'dish', kindCode: 'dish', kindLabel: 'Plat', unitId: 'unit', unitCode: 'unit', unitLabel: 'Unité', mediaIds: [], available: true, position: '1', dietaryTagCodes: [], allergenCodes: [], cuisineTypeCodes: ['creole'] }] }],
      unavailableReason: null,
    },
    cuisine: {
      codes: ['creole'],
      options: [{ id: 'creole', code: 'creole', label: 'Créole' }, { id: 'metropolitan', code: 'metropolitan', label: 'Française' }],
      unavailableReason: null,
    },
    activity: { durationMin: '120', minParticipants: '2', maxParticipants: '12', difficultyLevel: 'facile', guideRequired: true, minAge: '8', equipmentProvided: 'Casque', unavailableReason: null },
    event: { startDate: '', endDate: '', startTime: '', endTime: '', recurring: false, recurrenceText: '', occurrences: [], unavailableReason: null },
    itinerary: {
      distanceKm: '8.5',
      durationMin: '180',
      difficultyLevel: 'modéré',
      elevationPositiveM: '420',
      elevationNegativeM: '420',
      loop: true,
      openStatus: 'open',
      statusNote: '',
      practiceOptions: [{ id: 'walk', code: 'walk', label: 'Randonnée' }],
      practiceCodes: ['walk'],
      stages: [{ recordId: 'st1', name: 'Départ', description: 'Parking', position: '1' }],
      sectionsCount: 1,
      profilesCount: 1,
      geometrySummary: 'Trace GPX',
      traceEditable: false,
      unavailableReason: null,
    },
    openings: {
      periods: [{ recordId: 'op1', order: '1', bucket: 'current', label: 'Standard', seasonTypeCode: 'high_season', startDate: '', endDate: '', allYears: true, recurrence: 'always', isClosure: false, closedDays: [], weekdays: [{ code: 'monday', label: 'lundi', slots: [{ start: '09:00', end: '17:00' }] }] }],
      periodTypeOptions: [
        { code: 'high_season', label: 'Haute saison', color: '#176b6a', allYear: false },
        { code: 'mid_season', label: 'Mi-saison', color: '#c08a3e', allYear: false },
        { code: 'off_season', label: 'Hors saison', color: '#8a8f99', allYear: false },
        { code: 'year_round', label: 'Annuelle', color: '#2f8f6b', allYear: true },
      ],
      unavailableReason: null,
    },
    // Mirrors the parser's UNLOADED output (§19): empty interactions/topics + the default
    // "not loaded" reasons — the list_object_crm enrichment is what clears them. Tests that
    // need the loaded state override interactions/topics and null the reasons.
    providerFollowUp: {
      notes: [{ id: 'n1', body: 'Relance qualité', audience: 'private', category: 'followup', isPinned: false, isArchived: false, canEdit: false, canDelete: false, language: 'fr', createdAt: '2026-01-01T08:00:00Z', updatedAt: '2026-01-02T08:00:00Z', createdById: 'u1', createdByName: 'OTI', createdByAvatarUrl: '' }],
      interactions: [],
      topics: [],
      interactionsUnavailableReason: "Le live actuel n'expose pas encore les interactions CRM prestataire dans le workspace objet.",
      tasksUnavailableReason: "Le live actuel n'expose pas encore les taches CRM prestataire dans le workspace objet.",
    },
    relationships: {
      organizationLinks: [{ id: 'org1', source: 'org_link', type: 'ORG', name: 'OTI du Sud', status: 'active', roleId: 'publisher', roleCode: 'publisher', roleLabel: 'Publisher', isPrimary: true, note: '', contacts: [] }],
      actors: [{ id: 'a1', displayName: 'Marie Guide', firstName: 'Marie', lastName: 'Guide', gender: '', roleId: 'operator', roleCode: 'operator', roleLabel: 'Opérateur', visibility: 'public', isPrimary: true, validFrom: '', validTo: '', note: '', contacts: [] }],
      relatedObjects: [{ id: 'rel1', name: 'Sentier voisin', type: 'ITI', status: 'published', relationTypeId: 'near', relationTypeCode: 'near', relationTypeLabel: 'À proximité', direction: 'out', note: '5 min', distanceM: '400' }],
      orgRoleOptions: [
        { id: 'publisher', code: 'publisher', label: 'Publisher principal' },
        { id: 'contributor', code: 'contributor', label: 'ORG contributrice' },
      ],
      orgOptions: [{ id: 'ORG0000000000001', name: 'OTI du Sud' }],
      actorRoleOptions: [{ id: 'operator', code: 'operator', label: 'Exploitant' }],
      organizationLinkWriteUnavailableReason: null,
      actorWriteUnavailableReason: null,
      actorConsentUnavailableReason: null,
      relatedObjectWriteUnavailableReason: null,
    },
    memberships: {
      campaignOptions: [{ id: 'c2026', code: '2026', label: 'Campagne 2026' }],
      tierOptions: [{ id: 'std', code: 'standard', label: 'Standard' }],
      scopeOptions: [{ orgObjectId: 'org1', label: 'OTI du Sud', isPrimary: true }],
      items: [{ recordId: 'mem1', scope: 'object', orgObjectId: 'org1', orgLabel: 'OTI du Sud', campaignId: 'c2026', campaignCode: '2026', campaignLabel: 'Campagne 2026', tierId: 'std', tierCode: 'standard', tierLabel: 'Standard', status: 'paid', startsAt: '2026-01-01', endsAt: '', paymentDate: '', metadataJson: '', visibilityImpact: 'Active' }],
      unavailableReason: null,
    },
    legal: {
      typeOptions: [],
      records: [],
      compliance: { complianceStatus: 'unknown', requiredCount: 0, validCount: 0, expiringCount: 0, missingCount: 0, compliancePercentage: 0, details: [] },
      unavailableReason: null,
    },
    publication: {
      status: 'published',
      publishedAt: '2026-01-02',
      isEditing: true,
      moderation: { availability: 'available', pendingCount: 0, unavailableReason: null, items: [] },
      printPublications: { availability: 'available', selectionCount: 0, unavailableReason: null, items: [] },
    },
    syncIdentifiers: {
      objectCreatedAt: '2026-01-01',
      objectUpdatedAt: '2026-01-02',
      objectUpdatedAtSource: 'manual',
      externalIdentifiers: [{ id: 'x1', organizationObjectId: 'org1', sourceSystem: 'OTI', externalId: 'HOT-1', lastSyncedAt: '2026-01-02', createdAt: '2026-01-01', updatedAt: '2026-01-02' }],
      origins: [],
      externalIdentifiersVisibilityNote: null,
      originsVisibilityNote: null,
    },
    tags: {
      displayed: [
        { tagId: 't1', slug: 'hotel-4', label: 'Hôtel 4★', color: '#14b8a6' },
        { tagId: 't2', slug: 'cuisine', label: 'Cuisine', color: '#f97316' },
      ],
      library: [],
    },
    sustainability: {
      categories: [
        {
          id: 'cat-energy',
          code: 'CAT_ENERGY',
          label: 'Énergie',
          description: 'Réduction de la consommation énergétique.',
          actions: [
            {
              id: 'sa-led',
              code: 'SA_LED',
              label: 'LED généralisée',
              description: 'Éclairage LED sur la majorité des zones.',
              selected: true,
              note: '',
              documentId: '',
            },
            {
              id: 'sa-audit',
              code: 'SA_AUDIT',
              label: 'Audit énergétique',
              description: 'Audit énergétique réalisé dans les 3 dernières années.',
              selected: false,
              note: '',
              documentId: '',
            },
          ],
        },
      ],
      equivalentLabels: [],
    },
    distribution: {
      channels: [
        {
          id: 'ch-booking',
          code: 'BK',
          name: 'Booking',
          url: 'booking.com/le-bel-air',
          syncStatus: 'Sync OK · il y a 12 min',
          syncTone: 'ok',
          group: 'booking',
        },
      ],
      readonlyReason: "Les canaux sont projetés depuis l'acteur opérateur — le contrat d'écriture actor_channel est différé.",
    },
    provider: {
      siret: '44851998300012',
      companyName: 'SARL Domaine du Bel Air',
      sireneVerified: true,
      legalForm: 'SARL',
      nafCode: '55.10Z',
      consularChamber: 'CCI',
      cfeOrganization: 'CCI Réunion',
      directorFullName: 'Mr Franck Versluys',
      directorEmail: 'contact@domaine-bel-air.fr',
      directorPhone: '+262 000',
      address: '1 rue du Test, Saint-Pierre',
      incorporationDate: '12/03/2010',
      readonlyReason: 'Compléments éditables via les modules Légal et Acteurs — branchement direct différé.',
    },
  };
}
