import type { ObjectWorkspacePermissions } from '../../../services/object-workspace';
import type { ObjectWorkspaceModules, WorkspaceTranslatableField } from '../../../services/object-workspace-parser';

function tf(value: string): WorkspaceTranslatableField {
  return { baseValue: value, values: { fr: value } };
}

export const allowAll = new Proxy(
  {},
  {
    get: () => ({
      canDirectWrite: true,
      canPrepareProposal: true,
      canSubmitProposal: true,
      disabledReason: null,
      canEditPlaceDescriptions: true,
      canEditPlaceMedia: true,
      canEditPlaces: true,
      canEditZones: true,
    }),
  },
) as ObjectWorkspacePermissions;

export function fullModulesFixture(): ObjectWorkspaceModules {
  return {
    generalInfo: {
      name: 'Domaine du Bel Air',
      nameTranslations: {},
      businessTimezone: 'Indian/Reunion',
      commercialVisibility: 'active',
      regionCode: 'RE',
      status: 'published',
      publishedAt: '2026-01-02',
      isEditing: true,
    },
    taxonomy: { domains: [], unavailableReason: null },
    descriptions: {
      localLanguage: 'fr',
      activeLanguage: 'fr',
      availableLanguages: ['fr', 'en'],
      object: {
        recordId: 'd1',
        scope: 'object',
        placeId: null,
        label: 'Objet',
        visibility: 'public',
        description: tf('Description principale'),
        chapo: tf('Chapo'),
        adaptedDescription: tf('Adaptée'),
        mobileDescription: tf('Mobile'),
        editorialDescription: tf('Editoriale'),
      },
      places: [
        {
          recordId: 'pd1',
          scope: 'place',
          placeId: 'p1',
          label: 'Belvédère',
          visibility: 'public',
          description: tf('Vue sur le cirque'),
          chapo: tf(''),
          adaptedDescription: tf(''),
          mobileDescription: tf(''),
          editorialDescription: tf(''),
        },
      ],
    },
    location: {
      main: {
        recordId: 'l1',
        address1: '1 rue du Test',
        address1Suite: '',
        address2: '',
        address3: '',
        postcode: '97410',
        city: 'Saint-Pierre',
        codeInsee: '',
        lieuDit: '',
        direction: '',
        latitude: '-21.3',
        longitude: '55.4',
        zoneTouristique: 'Sud',
      },
      places: [],
      zoneCodes: [],
    },
    contacts: {
      objectItems: [
        {
          id: 'c1',
          kindId: 'k1',
          kindCode: 'phone',
          kindLabel: 'Téléphone',
          roleId: '',
          roleCode: '',
          roleLabel: '',
          value: '+262 000',
          isPublic: true,
          isPrimary: true,
          position: '0',
        },
      ],
      kindOptions: [{ id: 'k1', code: 'phone', label: 'Téléphone' }],
      roleOptions: [],
      relatedActorContactsCount: 0,
      relatedOrganizationContactsCount: 0,
    },
    media: {
      typeOptions: [
        { id: 'mt1', code: 'image', label: 'Image' },
        { id: 'mt2', code: 'pdf', label: 'PDF' },
      ],
      tagOptions: [],
      objectItems: [
        {
          id: 'm1',
          scope: 'object',
          placeId: null,
          scopeLabel: 'Objet',
          typeId: 'mt1',
          typeCode: 'image',
          typeLabel: 'Image',
          title: 'Hero image',
          titleTranslations: {},
          description: 'Façade',
          descriptionTranslations: {},
          url: '',
          credit: '',
          visibility: 'public',
          position: '0',
          width: '',
          height: '',
          rightsExpiresAt: '',
          kind: 'image',
          isMain: true,
          isPublished: true,
          tags: [],
        },
      ],
      placeItems: [],
      placeScopeUnavailableReason: null,
    },
    characteristics: {
      languageOptions: [{ id: 'fr', code: 'fr', label: 'Français' }, { id: 'en', code: 'en', label: 'Anglais' }],
      languageLevelOptions: [{ id: 'native', code: 'native', label: 'Courant' }],
      selectedLanguages: [{ languageId: 'fr', code: 'fr', label: 'Français', levelId: 'native', levelCode: 'native', levelLabel: 'Courant' }],
      paymentOptions: [{ id: 'card', code: 'card', label: 'CB' }, { id: 'cash', code: 'cash', label: 'Espèces' }],
      selectedPaymentCodes: ['card'],
      environmentOptions: [{ id: 'garden', code: 'garden', label: 'Jardin' }],
      selectedEnvironmentCodes: [],
      amenityGroups: [
        { familyCode: 'accessibility', familyLabel: 'Accessibilité', options: [{ id: 'pmr', code: 'pmr_access', label: 'Accès PMR' }] },
        { familyCode: 'services', familyLabel: 'Services', options: [{ id: 'wifi', code: 'wifi', label: 'Wi-Fi' }] },
      ],
      selectedAmenityCodes: ['wifi'],
      unavailableReason: null,
    },
    capacityPolicies: {
      metricOptions: [{ id: 'cap', code: 'capacity_total', label: 'Capacité totale' }],
      capacityItems: [{ recordId: 'cap1', metricId: 'cap', metricCode: 'capacity_total', metricLabel: 'Capacité totale', unit: 'pers.', value: '48', effectiveFrom: '', effectiveTo: '' }],
      groupPolicy: { minSize: '8', maxSize: '40', groupOnly: false, notes: 'Sur réservation' },
      petPolicy: { hasPolicy: true, accepted: false, conditions: 'Petits animaux' },
      unavailableReason: null,
    },
    distinctions: {
      distinctionGroups: [
        {
          schemeCode: 'stars',
          schemeLabel: 'Étoiles',
          items: [{ recordId: 'di1', schemeId: 'stars', schemeCode: 'stars', schemeLabel: 'Étoiles', valueId: '4', valueCode: '4', valueLabel: '4 étoiles', status: 'active', awardedAt: '2025-01-01', validUntil: '', disabilityTypesCovered: [] }],
        },
      ],
      accessibilityLabels: [{ recordId: 'acc1', schemeId: 'acc', schemeCode: 'acc', schemeLabel: 'Accessibilité', valueId: 'pmr', valueCode: 'pmr', valueLabel: 'Tourisme Handicap', status: 'active', awardedAt: '', validUntil: '', disabilityTypesCovered: ['moteur'] }],
      accessibilityAmenityCoverage: [{ code: 'pmr_access', label: 'Accès PMR', disabilityTypes: ['moteur'] }],
      schemeOptions: [],
      unavailableReason: null,
    },
    pricing: {
      priceKindOptions: [{ id: 'adult', code: 'adult', label: 'Adulte' }],
      priceUnitOptions: [{ id: 'person', code: 'person', label: 'Par personne' }],
      prices: [{ recordId: 'pr1', kindId: 'adult', kindCode: 'adult', kindLabel: 'Adulte', unitId: 'person', unitCode: 'person', unitLabel: 'Par personne', amount: '12', amountMax: '', currency: 'EUR', seasonCode: '', indicationCode: '', ageMinEnfant: '', ageMaxEnfant: '', ageMinJunior: '', ageMaxJunior: '', validFrom: '', validTo: '', conditions: '', source: '', periods: [] }],
      discounts: [],
      promotions: [],
      promotionsUnavailableReason: null,
      unavailableReason: null,
    },
    rooms: {
      viewTypeOptions: [],
      amenityOptions: [{ id: 'wifi', code: 'wifi', label: 'Wi-Fi' }],
      mediaOptions: [],
      items: [{ recordId: 'r1', code: 'std', name: 'Chambre standard', nameTranslations: {}, description: '', descriptionTranslations: {}, capacityAdults: '2', capacityChildren: '0', capacityTotal: '2', sizeSqm: '22', bedConfig: 'Double', bedConfigTranslations: {}, quantity: '12', floorLevel: '', viewTypeId: '', viewTypeCode: '', viewTypeLabel: '', basePrice: '165', currency: 'EUR', accessible: false, published: true, position: '1', amenityCodes: ['wifi'], mediaIds: [] }],
      unavailableReason: null,
    },
    meetingRooms: {
      equipmentOptions: [],
      items: [{ recordId: 'mr1', name: 'Salle Bras-Long', nameTranslations: {}, areaM2: '78', capacityTheatre: '60', capacityU: '32', capacityClassroom: '32', capacityBoardroom: '20', equipmentCodes: [] }],
      unavailableReason: null,
    },
    menus: {
      categoryOptions: [{ id: 'carte', code: 'carte', label: 'Carte' }],
      dietaryTagOptions: [],
      allergenOptions: [],
      cuisineTypeOptions: [{ id: 'creole', code: 'creole', label: 'Créole' }],
      priceKindOptions: [{ id: 'dish', code: 'dish', label: 'Plat' }],
      priceUnitOptions: [{ id: 'unit', code: 'unit', label: 'Unité' }],
      mediaOptions: [],
      items: [{ recordId: 'menu1', categoryId: 'carte', categoryCode: 'carte', categoryLabel: 'Carte', name: 'Carte midi', description: '', active: true, visibility: 'public', position: '1', items: [{ recordId: 'mi1', name: 'Cari', description: '', price: '18', currency: 'EUR', kindId: 'dish', kindCode: 'dish', kindLabel: 'Plat', unitId: 'unit', unitCode: 'unit', unitLabel: 'Unité', mediaIds: [], available: true, position: '1', dietaryTagCodes: [], allergenCodes: [], cuisineTypeCodes: ['creole'] }] }],
      unavailableReason: null,
    },
    activity: { durationMin: '120', minParticipants: '2', maxParticipants: '12', difficultyLevel: 'facile', guideRequired: true, minAge: '8', equipmentProvided: 'Casque', unavailableReason: null },
    event: { startDate: '', endDate: '', startTime: '', endTime: '', recurring: false, recurrenceText: '', occurrences: [], unavailableReason: null },
    itinerary: {
      distanceKm: '8.5',
      durationMin: '180',
      difficultyLevel: 'modéré',
      elevationPositiveM: '420',
      elevationNegativeM: '420',
      loop: true,
      openStatus: 'open',
      statusNote: '',
      practiceOptions: [{ id: 'walk', code: 'walk', label: 'Randonnée' }],
      practiceCodes: ['walk'],
      stages: [{ recordId: 'st1', name: 'Départ', description: 'Parking', position: '1' }],
      sectionsCount: 1,
      profilesCount: 1,
      geometrySummary: 'Trace GPX',
      traceEditable: false,
      unavailableReason: null,
    },
    openings: {
      periods: [{ recordId: 'op1', order: '1', bucket: 'current', label: 'Standard', startDate: '', endDate: '', allYears: true, closedDays: [], weekdays: [{ code: 'monday', label: 'lundi', slots: [{ start: '09:00', end: '17:00' }] }] }],
      unavailableReason: null,
    },
    providerFollowUp: { notes: [{ id: 'n1', body: 'Relance qualité', audience: 'private', category: 'followup', isPinned: false, isArchived: false, canEdit: false, canDelete: false, language: 'fr', createdAt: '2026-01-01T08:00:00Z', updatedAt: '2026-01-02T08:00:00Z', createdById: 'u1', createdByName: 'OTI', createdByAvatarUrl: '' }], interactionsUnavailableReason: null, tasksUnavailableReason: null },
    relationships: {
      organizationLinks: [{ id: 'org1', source: 'org_link', type: 'ORG', name: 'OTI du Sud', status: 'active', roleId: 'publisher', roleCode: 'publisher', roleLabel: 'Publisher', note: '', contacts: [] }],
      actors: [{ id: 'a1', displayName: 'Marie Guide', firstName: 'Marie', lastName: 'Guide', gender: '', roleId: 'operator', roleCode: 'operator', roleLabel: 'Opérateur', visibility: 'public', isPrimary: true, validFrom: '', validTo: '', note: '', contacts: [] }],
      relatedObjects: [{ id: 'rel1', name: 'Sentier voisin', type: 'ITI', status: 'published', relationTypeId: 'near', relationTypeCode: 'near', relationTypeLabel: 'À proximité', direction: 'out', note: '5 min', distanceM: '400' }],
      organizationLinkWriteUnavailableReason: null,
      actorWriteUnavailableReason: null,
      actorConsentUnavailableReason: null,
      relatedObjectWriteUnavailableReason: null,
    },
    memberships: {
      campaignOptions: [{ id: 'c2026', code: '2026', label: 'Campagne 2026' }],
      tierOptions: [{ id: 'std', code: 'standard', label: 'Standard' }],
      scopeOptions: [{ orgObjectId: 'org1', label: 'OTI du Sud', isPrimary: true }],
      items: [{ recordId: 'mem1', scope: 'object', orgObjectId: 'org1', orgLabel: 'OTI du Sud', campaignId: 'c2026', campaignCode: '2026', campaignLabel: 'Campagne 2026', tierId: 'std', tierCode: 'standard', tierLabel: 'Standard', status: 'paid', startsAt: '2026-01-01', endsAt: '', paymentDate: '', metadataJson: '', visibilityImpact: 'Active' }],
      unavailableReason: null,
    },
    legal: {
      typeOptions: [],
      records: [],
      compliance: { complianceStatus: 'unknown', requiredCount: 0, validCount: 0, expiringCount: 0, missingCount: 0, compliancePercentage: 0, details: [] },
      unavailableReason: null,
    },
    publication: {
      status: 'published',
      publishedAt: '2026-01-02',
      isEditing: true,
      moderation: { availability: 'available', pendingCount: 0, unavailableReason: null, items: [] },
      printPublications: { availability: 'available', selectionCount: 0, unavailableReason: null, items: [] },
    },
    syncIdentifiers: {
      objectCreatedAt: '2026-01-01',
      objectUpdatedAt: '2026-01-02',
      objectUpdatedAtSource: 'manual',
      externalIdentifiers: [{ id: 'x1', organizationObjectId: 'org1', sourceSystem: 'OTI', externalId: 'HOT-1', lastSyncedAt: '2026-01-02', createdAt: '2026-01-01', updatedAt: '2026-01-02' }],
      origins: [],
      externalIdentifiersVisibilityNote: null,
      originsVisibilityNote: null,
    },
  };
}
